// Sprachpaket Englisch: Texte der Oberfläche, Artikelkatalog, Startverlauf und typischer Vorrat.
// Schlüssel der Texte ist der deutsche Text aus index.html; {0}, {1} … sind eingesetzte Werte.
// Katalog im selben Format wie katalog.js: Einträge durch Komma getrennt, Synonyme durch „|“, „~“ = Falschschreibung.

(window.SPRACHPAKETE = window.SPRACHPAKETE || {}).en = {
  texte: {
    'Einkaufsliste': 'Shopping list',
    'Speichern fehlgeschlagen': 'Saving failed',
    'Supermarkt': 'Supermarket',
    'Drogerie': 'Drugstore',
    'Stück': 'pcs',
    '{0}: diesmal nicht': '{0}: not this time',
    'Rückgängig': 'Undo',
    '{0} gelöscht': '{0} deleted',
    'Auch die Stammartikel werden entfernt.': 'Regular items will be removed too.',
    'Die ganze Einkaufsliste löschen ({0} Artikel)?': { one: 'Delete the whole shopping list ({0} item)?', other: 'Delete the whole shopping list ({0} items)?' },
    'Liste gelöscht': 'List deleted',
    'Einkauf abgeschlossen ({0})': 'Shopping done ({0})',
    'Rezept · {0} Zutaten': { one: 'Recipe · {0} ingredient', other: 'Recipe · {0} ingredients' },
    'schon auf der Liste': 'already on the list',
    'Korrektur': 'correction',
    'zuordnen': 'assign',
    'Diesmal nicht': 'Not this time',
    'Löschen': 'Delete',
    'Zurückholen': 'Restore',
    'Abhaken': 'Check off',
    'Laden': 'Store',
    'Laden wählen': 'Choose store',
    'Die Liste ist leer.': 'The list is empty.',
    'Oben eintragen, scannen oder ein Rezept übernehmen.': 'Type above, scan a barcode or add a recipe.',
    'Nicht in diesem Laden ({0})': 'Not in this store ({0})',
    'Diesmal nicht:': 'Not this time:',
    'Ganze Liste löschen': 'Delete whole list',
    'Einkauf abschließen · {0} erledigt': 'Finish shopping · {0} done',
    'Schnellauswahl': 'Quick picks',
    'Schnellauswahl zeigen': 'Show quick picks',
    'Schnellauswahl ausblenden': 'Hide quick picks',
    'Kein Rezept {0}': 'No recipe {0}',
    'Noch keine Rezepte gespeichert': 'No recipes saved yet',
    'Abbrechen': 'Cancel',
    'Nicht mehr anheften': 'Unpin',
    'Immer in der Schnellauswahl zeigen': 'Always show in quick picks',
    'Nicht mehr vorschlagen': 'Stop suggesting',
    'Verwalten unter Einstellungen → Schnellauswahl.': 'Manage under Settings → Quick picks.',
    'Artikel': 'Item',
    'Fertig': 'Done',
    'Name': 'Name',
    'Menge': 'Quantity',
    'Weniger': 'Less',
    'Mehr': 'More',
    'Abteilung': 'Section',
    'Marke / Notiz': 'Brand / note',
    'z. B. Alnatura, 1,5 %': 'e.g. organic, semi-skimmed',
    'Wird immer benötigt': 'Always needed',
    'Steht nach jedem Einkauf von selbst wieder auf der Liste': 'Goes back on the list by itself after every shop',
    'Von der Liste löschen': 'Delete from list',
    'Abteilung wählen. Die App merkt sich das für diesen Artikel.': 'Choose a section. The app remembers it for this item.',
    'Angeheftet, immer zuerst': 'Pinned, always first',
    'Lösen': 'Unpin',
    'Danach automatisch die häufigsten Käufe, ohne Stammartikel. Auch in der Schnellauswahl: Chip lange drücken.':
      'Then your most frequent purchases, without regular items. In the quick picks you can also long-press a chip.',
    'Anheften': 'Pin',
    'Ausblenden': 'Hide',
    'Noch nichts gekauft.': 'Nothing bought yet.',
    'Ausgeblendet': 'Hidden',
    'Wieder zeigen': 'Show again',
    'Automatisch ({0})': 'Automatic ({0})',
    'Einstellungen': 'Settings',
    'Läden': 'Stores',
    'Standort gespeichert': 'location saved',
    '{0} Abteilungen': { one: '{0} section', other: '{0} sections' },
    'Laden hinzufügen': 'Add store',
    'Laden per Standort wählen': 'Choose store by location',
    'Beim Öffnen im Laden passendes Profil einstellen': 'When opened in a store, switch to that store',
    'Sprache': 'Language',
    'Gilt für Texte, Abteilungen und die Erkennung der Artikel. Schon eingetragene Artikel behalten ihren Namen.':
      'Applies to texts, sections and item recognition. Items already on the list keep their names.',
    'Darstellung': 'Appearance',
    'Automatisch': 'Automatic',
    'Hell': 'Light',
    'Dunkel': 'Dark',
    'Abteilungen farbig markieren': 'Colour-code sections',
    'Farbe je Bereich im Laden, die Beschriftung bleibt': 'One colour per store area, labels stay',
    'Abteilung in der Listenansicht zeigen': 'Show section in list view',
    'Name der Abteilung rechts neben dem Artikel': 'Section name to the right of the item',
    'Streifen': 'Stripes',
    'Farbige Zeilen': 'Coloured rows',
    'Nur in der Listenansicht, wenn das Eingabefeld leer ist': 'Only in list view, when the input field is empty',
    'Anzeigen': 'Show',
    'Beim Antippen': 'On tap',
    'Immer': 'Always',
    'Immer unter dem Eingabefeld. Nach oben wischen blendet sie aus, antippen oder nach unten wischen holt sie zurück.':
      'Always below the input field. Swipe up to hide them, tap or swipe down to bring them back.',
    'Erscheint, sobald du ins Eingabefeld tippst, und bei leerer Liste.': 'Appears as soon as you tap the input field, and when the list is empty.',
    'Anzahl': 'Number',
    'Artikel anheften': 'Pin an item',
    'Stammartikel': 'Regular items',
    'Entfernen': 'Remove',
    'Noch keine. Artikel antippen und „Wird immer benötigt“ einschalten.': 'None yet. Tap an item and turn on “Always needed”.',
    'Rezepte': 'Recipes',
    '{0} Zutaten': { one: '{0} ingredient', other: '{0} ingredients' },
    'Noch keine. Beim Übernehmen eines Rezepts einen Namen vergeben, dann im Eingabefeld mit #Name abrufen.':
      'None yet. Give a recipe a name when you add it, then call it up in the input field with #Name.',
    'Rezept-Fotos': 'Recipe photos',
    'Claude-API-Schlüssel (bleibt nur auf diesem Gerät)': 'Claude API key (stays on this device only)',
    'Ohne Schlüssel funktioniert „Zutaten übernehmen“ per Text weiterhin. Mit Schlüssel kostet ein Rezeptfoto etwa 2–3 Cent.':
      'Without a key, “Add ingredients” still works with pasted text. With a key, a recipe photo costs about 2–3 cents.',
    'Daten': 'Data',
    'Sicherung exportieren': 'Export backup',
    'Sicherung importieren': 'Import backup',
    'Verlauf und gelernte Zuordnungen löschen': 'Delete history and learned sections',
    '{0} Artikel im Verlauf · {1} gelernte Zuordnungen · {2} Katalogbegriffe': '{0} items in history · {1} learned sections · {2} catalogue terms',
    'Neuer Laden': 'New store',
    'Verlauf, gelernte Abteilungen und gespeicherte Barcodes löschen? Die aktuelle Liste bleibt.':
      'Delete history, learned sections and saved barcodes? The current list stays.',
    'Zurück': 'Back',
    'z. B. REWE Hauptstraße': 'e.g. Tesco High Street',
    'Laufweg': 'Route through the store',
    'Am Griff ziehen, um die Reihenfolge zu ändern. Haken entfernen, wenn es die Abteilung in diesem Laden nicht gibt.':
      'Drag the handle to change the order. Untick a section if this store doesn’t have it.',
    'In diesem Laden vorhanden': 'Available in this store',
    'Verschieben': 'Move',
    'Standort': 'Location',
    'Nicht gespeichert. Auf der Karte wählen oder im Laden stehend übernehmen, dann wählt die App diesen Laden automatisch.':
      'Not saved. Choose it on the map or save it while you are in the store; the app then picks this store automatically.',
    'Auf der Karte gewählt: {0}.': 'Chosen on the map: {0}.',
    'Auf der Karte gewählt.': 'Chosen on the map.',
    'Gespeichert (±{0} m).': 'Saved (±{0} m).',
    'Auf der Karte wählen': 'Choose on map',
    'Aktuellen Standort übernehmen': 'Use current location',
    'Standort entfernen': 'Remove location',
    'Laden löschen': 'Delete store',
    'Standort wird bestimmt': 'Finding location',
    'Standort nicht verfügbar': 'Location not available',
    '„{0}“ löschen?': 'Delete “{0}”?',
    'Sicherung einspielen? Die aktuellen Daten werden ersetzt (der API-Schlüssel bleibt).': 'Restore backup? The current data will be replaced (the API key stays).',
    'Sicherung eingespielt': 'Backup restored',
    'Datei konnte nicht gelesen werden': 'Could not read the file',
    'Standort wählen': 'Choose location',
    'Adresse oder Markt suchen': 'Search address or store',
    'Karte wird geladen': 'Loading map',
    'Standort übernehmen': 'Use this location',
    'Die Karte konnte nicht geladen werden. Bitte Internetverbindung prüfen.': 'The map could not be loaded. Please check your internet connection.',
    'Namen übernehmen': 'Use name',
    'Nadel gesetzt. Tippe auf einen Markt-Punkt, um auch den Namen zu übernehmen.': 'Pin placed. Tap a store dot to use its name as well.',
    'Zum Anzeigen der Märkte näher heranzoomen oder oben suchen.': 'Zoom in to see stores, or search above.',
    'Märkte werden gesucht …': 'Looking for stores …',
    '1 Markt: Punkt antippen oder Nadel per Tippen auf die Karte setzen.': '1 store: tap the dot, or tap the map to place a pin.',
    '{0} Märkte: Punkt antippen oder Nadel per Tippen auf die Karte setzen.': '{0} stores: tap a dot, or tap the map to place a pin.',
    'Hier keine Märkte gefunden. Nadel per Tippen auf die Karte setzen.': 'No stores found here. Tap the map to place a pin.',
    'Märkte gerade nicht abrufbar. Nadel per Tippen auf die Karte setzen.': 'Stores can’t be loaded right now. Tap the map to place a pin.',
    'Standort wird bestimmt …': 'Finding location …',
    'Adresse oder Markt oben suchen, oder die Karte verschieben und heranzoomen.': 'Search for an address or store above, or move the map and zoom in.',
    'Suche …': 'Searching …',
    'Suche gerade nicht erreichbar': 'Search not available right now',
    'Nichts gefunden': 'Nothing found',
    'Standort gespeichert: {0}': 'Location saved: {0}',
    'Erst bei einem Laden den Standort speichern': 'Save a location for a store first',
    'Laden: {0}': 'Store: {0}',
    'Kein gespeicherter Laden in der Nähe': 'No saved store nearby',
    'Nummer eingeben': 'Enter number',
    'Barcode in den Rahmen halten': 'Hold the barcode inside the frame',
    'EAN-Nummer (unter dem Barcode):': 'EAN number (below the barcode):',
    'Kamera nicht verfügbar. Zugriff in den Einstellungen erlauben oder Nummer eingeben.': 'Camera not available. Allow access in Settings or enter the number.',
    'Die Kamera geht nur, wenn die App über https geöffnet wird. Nummer eingeben geht trotzdem.':
      'The camera only works when the app is opened via https. Entering the number still works.',
    'Barcode {0}': 'Barcode {0}',
    'Produkt wird gesucht': 'Looking up product',
    'Schon einmal gescannt.': 'Scanned before.',
    'Gefunden. Name bei Bedarf kürzen.': 'Found. Shorten the name if you like.',
    'Nicht in der Produktdatenbank. Einmal benennen, dann merkt sich die App den Barcode.':
      'Not in the product database. Name it once and the app will remember the barcode.',
    'z. B. Alpro Haferdrink Barista 1 l': 'e.g. Oatly Barista 1 l',
    'Hinzufügen': 'Add',
    'auf der Liste': 'on the list',
    'Vorrat': 'pantry',
    'Rezept übernehmen': 'Add recipe',
    'Gespeicherte Rezepte': 'Saved recipes',
    'Im Foto oder Screenshot die Zutaten markieren (Text gedrückt halten), kopieren und hier einfügen.':
      'In a photo or screenshot, select the ingredients (press and hold the text), copy them and paste them here.',
    'Zutaten': 'Ingredients',
    '200 g Spaghetti&#10;2 Zehen Knoblauch&#10;1 Bund Basilikum': '200 g spaghetti&#10;2 cloves garlic&#10;1 bunch basil',
    'Zutaten übernehmen': 'Add ingredients',
    'Foto wählen und erkennen lassen': 'Choose photo and recognise',
    'Foto erkennen lassen (API-Schlüssel nötig)': 'Recognise photo (API key needed)',
    'Keine Zutaten erkannt': 'No ingredients recognised',
    'Foto wird ausgewertet': 'Analysing photo',
    'Auf dem Foto wurden keine Zutaten gefunden.': 'No ingredients found in the photo.',
    'Fehler bei der Erkennung.': 'Recognition failed.',
    'Was brauchst du?': 'What do you need?',
    'Abwählen, was noch im Vorrat ist. Name, Menge und Abteilung lassen sich antippen und ändern.':
      'Untick what you already have. Tap name, quantity or section to change them.',
    'Übernehmen': 'Include',
    'Name und Menge': 'Name and quantity',
    'Als Rezept speichern (optional, alle Zutaten)': 'Save as recipe (optional, all ingredients)',
    'Name, z. B. Chili sin Carne': 'Name, e.g. Veggie chili',
    '1 Artikel hinzufügen': 'Add 1 item',
    '{0} Artikel hinzufügen': 'Add {0} items',
    '{0} und Rezept speichern': '{0} and save recipe',
    'Nur Rezept speichern': 'Save recipe only',
    'Rezept gespeichert, abrufen mit #{0}': 'Recipe saved, call it up with #{0}',
    'Es gibt schon ein Rezept „#{0}“. Ersetzen?': 'There is already a recipe “#{0}”. Replace it?',
    'Name (abrufen mit #Name)': 'Name (call up with #Name)',
    'Zutat, z. B. 500 g Hackfleisch': 'Ingredient, e.g. 500 g minced beef',
    'Auf die Liste': 'Add to list',
    'Rezept löschen': 'Delete recipe',
    '„#{0}“ gibt es schon': '“#{0}” already exists',
    'Name fehlt': 'Name missing',
    'Rezept „#{0}“ löschen?': 'Delete recipe “#{0}”?',
    'API-Schlüssel ungültig. Bitte in den Einstellungen prüfen.': 'Invalid API key. Please check it in Settings.',
    'Claude ist gerade ausgelastet. Bitte gleich noch einmal versuchen.': 'Claude is busy right now. Please try again in a moment.',
    'Fehler {0}': 'Error {0}',
    'Die Anfrage wurde abgelehnt. Bitte den Text einfügen.': 'The request was declined. Please paste the text instead.',
    'Die Antwort war zu lang. Bitte einen kleineren Ausschnitt fotografieren.': 'The answer was too long. Please photograph a smaller section.',
    'Keine offenen Artikel zum Teilen': 'No open items to share',
    'Einkaufsliste ({0} Artikel)': { one: 'Shopping list ({0} item)', other: 'Shopping list ({0} items)' },
    'Zum Abhaken öffnen:': 'Open to check off:',
    'Liste teilen': 'Share list',
    'Teilen': 'Share',
    'Kopieren': 'Copy',
    'Kopiert, jetzt in eine Nachricht einfügen': 'Copied, now paste it into a message',
    'Der Link ist unvollständig oder beschädigt': 'The link is incomplete or damaged',
    'Der Link stammt aus einer neueren Version der App': 'The link comes from a newer version of the app',
    'Es ist schon eine geteilte Liste mit abgehakten Artikeln offen. Durch die neue ersetzen?':
      'A shared list with checked items is already open. Replace it with the new one?',
    'geteilt am {0}': 'shared on {0}',
    '{0} Artikel': { one: '{0} item', other: '{0} items' },
    'Die geteilte Liste ist leer.': 'The shared list is empty.',
    'Erledigt zurückschicken · {0} von {1}': 'Send back · {0} of {1} done',
    'Geteilte Liste schließen? Die Häkchen gehen verloren. Schicke vorher die Rückmeldung, falls noch nicht geschehen.':
      'Close the shared list? The ticks will be lost. Send your feedback first if you haven’t yet.',
    'Einkauf erledigt: {0} von {1} Artikeln': 'Shopping done: {0} of {1} items',
    'Nicht bekommen:': 'Couldn’t get:',
    'In die Liste übernehmen:': 'Apply to the list:',
    'Rückmeldung schicken': 'Send feedback',
    'Rückmeldung': 'Feedback',
    '{0} gekauft, {1} nicht bekommen.': '{0} bought, {1} not available.',
    'Gekauft': 'Bought',
    'Nicht bekommen (bleibt offen)': 'Not available (stays open)',
    '1 Artikel steht nicht mehr auf dieser Liste.': '1 item is no longer on this list.',
    '{0} Artikel stehen nicht mehr auf dieser Liste.': '{0} items are no longer on this list.',
    'Nutzt du die App vom Home-Bildschirm? Dann kopiere den Link aus der Nachricht und füge ihn dort ins Eingabefeld ein. Safari und die App haben getrennte Listen.':
      'Using the app from your home screen? Then copy the link from the message and paste it into the input field there. Safari and the app keep separate lists.',
    '{0} als gekauft abhaken': 'Check off {0} as bought',
    'Nichts abzuhaken': 'Nothing to check off',
    '{0} abgehakt': '{0} checked off',
    // Abteilungen
    'Gemüse': 'Vegetables',
    'Obst': 'Fruit',
    'Brot & Backwaren': 'Bread & Bakery',
    'Molkerei & Eier': 'Dairy & Eggs',
    'Käse': 'Cheese',
    'Fleisch & Wurst': 'Meat & Sausages',
    'Fisch': 'Fish',
    'Tofu, Frischteig & Feinkost': 'Tofu, Fresh Pasta & Deli',
    'Frühstück, Kaffee & Tee': 'Breakfast, Coffee & Tea',
    'Nudeln, Reis & Beilagen': 'Pasta, Rice & Grains',
    'Konserven & Saucen': 'Tins, Jars & Sauces',
    'Öl, Essig & Gewürze': 'Oil, Vinegar & Spices',
    'Backzutaten & Nüsse': 'Baking & Nuts',
    'Süßes & Snacks': 'Sweets & Snacks',
    'H-Milch & Pflanzendrinks': 'Long-life & Plant Milk',
    'Getränke': 'Drinks',
    'Tiefkühl': 'Frozen',
    'Drogerie & Körperpflege': 'Health & Beauty',
    'Haushalt & Putzen': 'Household & Cleaning',
    'Sonstiges': 'Other',
    // Bereiche und Farbschemata
    'Obst & Gemüse': 'Fruit & Veg',
    'Brot': 'Bread',
    'Kühlregal': 'Chilled',
    'Fleisch & Fisch': 'Meat & Fish',
    'Trockenwaren': 'Dry goods',
    'Drogerie & Haushalt': 'Health, Beauty & Household',
    'Markt': 'Market',
    'Farben passend zur Ware: Gemüse grün, Brot gelb, Kühlregal blau, Fleisch rot.': 'Colours that match the goods: vegetables green, bread yellow, chilled blue, meat red.',
    'Kontrast': 'Contrast',
    'Größtmöglicher Abstand zwischen benachbarten Bereichen, auch bei Rot-Grün-Schwäche.': 'Maximum difference between neighbouring areas, also for red-green colour blindness.',
    'Ruhig': 'Calm',
    'Nur vier Farben für die großen Zonen: Frisch, Kühlung, Trocken, Drogerie.': 'Only four colours for the main zones: fresh, chilled, dry, household.',
    'Frisch': 'Fresh',
    'Kühlung': 'Chilled',
    'Trocken & Getränke': 'Dry goods & Drinks',
    // Feste Texte im HTML
    'Liste': 'List',
    'Geteilte Liste': 'Shared list',
    'Schließen': 'Close',
    'Artikel hinzufügen': 'Add item',
    'Barcode scannen': 'Scan barcode',
    'Einkauf abschließen': 'Finish shopping',
  },

  katalog: {
    gemuese: `
      Tomatoes|Tomato|Vine tomatoes|Beef tomatoes|~Tomatos|~Tomatoe, Cherry tomatoes|Cherry tomato|Plum tomatoes|Baby plum tomatoes|Grape tomatoes,
      Cucumber|Cucumbers|Mini cucumbers, Courgettes|Courgette|Zucchini|Zucchinis, Peppers|Bell peppers|Bell pepper|Red pepper|Green pepper|Capsicum|Sweet pointed peppers,
      Carrots|Carrot|Baby carrots, Potatoes|Potato|Baby potatoes|New potatoes|Baking potatoes|Maris Piper|Russet potatoes|~Potatos|~Potatoe,
      Sweet potatoes|Sweet potato|Yams, Onions|Onion|Red onions|Red onion|White onions|Brown onions|Yellow onions|Shallots|Shallot,
      Spring onions|Spring onion|Green onions|Scallions, Garlic|Garlic bulb|Garlic cloves, Ginger|Ginger root|Fresh ginger, Turmeric root,
      Broccoli|Tenderstem broccoli|~Brocoli|~Brocolli, Cauliflower, Romanesco, Mushrooms|Mushroom|Button mushrooms|Chestnut mushrooms|Portobello mushrooms|Closed cup mushrooms,
      Oyster mushrooms, Shiitake mushrooms|Shiitake, Chanterelles, Lettuce|Salad|Mixed salad|Salad leaves|Mixed leaves|Salad bag,
      Iceberg lettuce|Iceberg, Romaine lettuce|Romaine|Cos lettuce|Little gem|Baby gem, Lamb’s lettuce|Lambs lettuce|Corn salad, Rocket|Arugula|Wild rocket,
      Endive|Chicory, Radicchio, Spinach|Baby spinach|Spinach leaves, Leeks|Leek, Celery|Celery sticks, Celeriac, Soup vegetables|Stew pack,
      Aubergines|Aubergine|Eggplant|Eggplants, Squash|Butternut squash|Pumpkin|Hokkaido pumpkin, Beetroot|Beets|Cooked beetroot, Radishes|Radish,
      Daikon|White radish, Kohlrabi, White cabbage|Cabbage|Pointed cabbage|Sweetheart cabbage, Red cabbage, Savoy cabbage, Brussels sprouts|Sprouts,
      Kale|Cavolo nero, Chinese cabbage|Napa cabbage, Pak choi|Bok choy|Pak choy, Fennel, Asparagus|Green asparagus|White asparagus,
      Corn on the cob|Sweetcorn cobs, Sugar snap peas|Mangetout|Snow peas, Green beans|Fine beans|French beans|Runner beans|String beans,
      Avocados|Avocado, Swiss chard|Chard, Parsnips|Parsnip, Jerusalem artichokes, Artichokes|Artichoke, Okra, Turnips|Turnip|Swede|Rutabaga,
      Chillies|Chilli|Chili peppers|Chilies|Red chilli|Jalapeños|Jalapenos, Fresh herbs|Herbs|Potted herbs, Basil|Fresh basil, Parsley|Flat leaf parsley|Curly parsley,
      Chives, Coriander|Cilantro|Fresh coriander, Dill, Mint|Fresh mint|Peppermint, Rosemary, Thyme, Sage, Lemongrass, Cress|Watercress, Sprouts|Bean sprouts|Alfalfa,
      Vegetables|Fresh vegetables|Veg, Stir fry vegetables|Stir fry mix, Salad vegetables
    `,
    obst: `
      Apples|Apple|Gala apples|Pink Lady|Braeburn|Granny Smith, Bananas|Banana, Pears|Pear, Oranges|Orange|Navel oranges, Mandarins|Clementines|Satsumas|Tangerines|Easy peelers,
      Lemons|Lemon, Limes|Lime, Grapefruit|Grapefruits, Grapes|Red grapes|Green grapes|Seedless grapes, Strawberries|Strawberry,
      Raspberries|Raspberry, Blueberries|Blueberry, Blackberries|Blackberry, Redcurrants|Blackcurrants|Currants, Gooseberries,
      Berries|Fresh berries|Mixed berries, Cherries|Cherry, Peaches|Peach|Flat peaches, Nectarines|Nectarine, Apricots|Apricot,
      Plums|Plum, Kiwis|Kiwi|Kiwi fruit, Mangoes|Mango|Mangos, Pineapple|Pineapples, Melon|Watermelon|Honeydew melon|Cantaloupe|Galia melon,
      Pomegranate|Pomegranates, Figs|Fig, Passion fruit, Papaya, Physalis, Persimmon|Sharon fruit|Kaki, Rhubarb, Fruit|Fresh fruit, Lychees|Lychee,
      Coconut, Quinces, Fresh dates
    `,
    brot: `
      Bread|Loaf|Wholemeal bread|Brown bread|White bread|Sourdough|Sourdough bread|Rye bread|Seeded bread|Granary bread, Sliced bread|Toast|Toast bread|Sandwich bread,
      Bread rolls|Rolls|Roll|Baps|Crusty rolls|Dinner rolls, Pretzels|Pretzel|Soft pretzels, Baguette|French stick, Ciabatta, Croissants|Croissant|Pain au chocolat,
      Crispbread|Ryvita, Rusks, Flatbread|Pitta|Pitta bread|Pita|Pita bread|Naan|Naan bread, Pumpernickel, Part baked rolls|Bake at home rolls,
      Burger buns|Buns|Brioche buns, Hot dog rolls|Hot dog buns, Cake|Cakes, Wraps|Wrap|Tortillas|Tortilla wraps|Flour tortillas, Bagels|Bagel,
      Muffins|English muffins, Doughnuts|Donuts, Brioche, Crumpets, Scones, Hot cross buns, Teacakes
    `,
    molkerei: `
      Milk|Whole milk|Semi-skimmed milk|Skimmed milk|Fresh milk|Full fat milk|Semi skimmed|Skimmed|1% milk|2% milk, Yogurt|Yoghurt|Natural yogurt|Plain yogurt|Fruit yogurt|~Yoghort,
      Greek yogurt|Greek yoghurt|Greek style yogurt, Skyr, Quark, Cream|Double cream|Single cream|Whipping cream|Heavy cream|Cooking cream,
      Sour cream|Soured cream, Crème fraîche|Creme fraiche, Butter|Salted butter|Unsalted butter|Spreadable butter, Garlic butter|Herb butter,
      Margarine|Spread|Vegetable spread, Eggs|Egg|Free range eggs|Organic eggs|Large eggs, Buttermilk, Kefir, Drinking yogurt|Yogurt drink,
      Pudding|Custard|Chocolate pudding|Rice pudding pots, Tzatziki, Chocolate milk|Milkshake|Flavoured milk, Iced coffee, Desserts|Dessert pots,
      Half and half|Coffee creamer, Clotted cream
    `,
    kaese: `
      Cheese|Cheese slices|Sliced cheese, Cheddar|Mature cheddar|Mild cheddar|Red Leicester, Gouda, Emmental|Emmentaler|Swiss cheese, Edam, Jarlsberg|Leerdammer,
      Grated cheese|Shredded cheese|Pizza cheese, Parmesan|Parmigiano|Grana Padano, Pecorino, Mozzarella|Buffalo mozzarella|Mini mozzarella,
      Burrata, Feta|Feta cheese, Halloumi|~Haloumi|~Halumi, Cream cheese|Philadelphia|Soft cheese, Cottage cheese, Mascarpone, Ricotta,
      Camembert, Brie, Goat’s cheese|Goats cheese|Goat cheese, Blue cheese|Stilton|Gorgonzola|Roquefort, Raclette cheese, Manchego,
      Wensleydale, Gruyère|Gruyere|Comté, Monterey Jack|Colby, Provolone, Paneer, Babybel, Cheese strings
    `,
    fleisch: `
      Mince|Minced beef|Ground beef|Beef mince|Pork mince|Minced meat|Ground meat, Chicken breast|Chicken breasts|Chicken fillets|Chicken breast fillets,
      Chicken|Whole chicken|Chicken thighs|Chicken drumsticks|Chicken legs|Chicken wings|Roast chicken, Turkey|Turkey breast|Turkey steaks|Turkey mince,
      Schnitzel|Escalope|Pork escalope|Veal escalope, Steak|Beef steak|Sirloin steak|Rump steak|Ribeye|Fillet steak, Beef|Stewing beef|Diced beef|Beef joint|Roast beef|Braising steak,
      Pork|Pork chops|Pork loin|Pork belly|Pork fillet|Pork tenderloin|Pulled pork|Pork shoulder, Lamb|Lamb chops|Leg of lamb|Lamb mince|Lamb shank,
      Meatballs|Burgers|Beef burgers|Hamburgers|Patties, Sausages|Pork sausages|Chipolatas|Cumberland sausages|Bratwurst,
      Hot dogs|Frankfurters|Wieners, Salami|Pepperoni, Ham|Cooked ham|Sliced ham|Honey roast ham, Prosciutto|Parma ham|Serrano ham|Cured ham,
      Bacon|Streaky bacon|Back bacon|Smoked bacon|Bacon lardons|Lardons|Pancetta, Cold cuts|Cooked meats|Deli meat|Lunch meat|Luncheon meat, Liver pâté|Pâté|Pate,
      Mortadella|Bologna, Chorizo, Kabanos|Cabanossi, Duck|Duck breast, Gyros|Kebab meat|Doner, Black pudding, Corned beef, Venison, Veal, Liver
    `,
    fisch: `
      Salmon|Salmon fillets|Wild salmon, Smoked salmon, Trout|Trout fillets, Smoked trout, Cod|Cod fillets|Haddock|Pollock|White fish|Fish fillets|Hake|Coley,
      Prawns|Shrimp|King prawns|Tiger prawns|Cooked prawns|Scampi, Herring|Pickled herring|Kippers|Rollmops, Mackerel|Smoked mackerel,
      Sea bream|Sea bass|Bream|Bass|Tilapia|Plaice|Sole, Squid|Calamari|Octopus, Mussels|Clams|Scallops|Oysters, Crab|Crab sticks|Surimi,
      Fish, Tuna steaks|Fresh tuna, Swordfish, Monkfish, Lobster
    `,
    kuehlveg: `
      Tofu|Smoked tofu|Silken tofu|Firm tofu, Tempeh, Seitan, Veggie burgers|Vegan burgers|Plant based burgers|Vegan sausages|Veggie sausages|Veggie mince|Vegan mince|Quorn,
      Falafel, Hummus|Houmous|Humous, Gnocchi, Fresh pasta|Tortellini|Ravioli|Tortelloni|Filled pasta, Pizza dough|Pizza base, Puff pastry, Shortcrust pastry,
      Filo pastry|Phyllo, Croissant dough|Cinnamon roll dough, Dips|Spreads|Vegan spread, Antipasti|Deli olives,
      Fresh pesto, Kimchi, Coleslaw|Potato salad|Prepared salad, Sandwiches|Ready wraps, Guacamole|Fresh salsa, Fresh soup|Chilled ready meals
    `,
    fruehstueck: `
      Oats|Porridge oats|Rolled oats|Oatmeal|Jumbo oats, Muesli|Granola|Crunchy granola|Fruit muesli|Porridge, Cereal|Cereals|Cornflakes|Breakfast cereal|Weetabix|Rice Krispies|Cheerios|Shreddies,
      Nutella|Chocolate spread|Hazelnut spread, Jam|Marmalade|Strawberry jam|Raspberry jam|Jelly|Preserves, Honey, Peanut butter, Almond butter|Nut butter|Cashew butter,
      Coffee|Coffee beans|Ground coffee|Espresso|Filter coffee, Coffee pods|Coffee capsules|Nespresso|Capsules, Instant coffee|Nescafé, Coffee filters|Filter papers,
      Tea|Tea bags|Black tea|Breakfast tea|Earl Grey|Fruit tea|Herbal tea, Green tea, Peppermint tea|Mint tea, Camomile tea|Chamomile tea, Ginger tea, Chai,
      Hot chocolate|Cocoa|Cocoa powder|Drinking chocolate, Chia seeds|Chia, Linseed|Flaxseed|Flax seeds, Protein powder|Whey, Maple syrup|Agave syrup|Golden syrup|Date syrup,
      Pancake mix, Ovaltine|Horlicks|Milo, Marmite|Vegemite, Lemon curd
    `,
    nudeln: `
      Spaghetti|~Spagetti|Spaghettini, Pasta|Noodles|Dried pasta, Penne, Fusilli, Farfalle, Rigatoni, Tagliatelle|Pappardelle|Fettuccine,
      Linguine, Macaroni|Elbow macaroni, Lasagne sheets|Lasagna sheets|Lasagna noodles, Wholewheat pasta|Whole wheat pasta, Egg noodles|Soup noodles|Vermicelli,
      Rice|Long grain rice|White rice|Brown rice|Easy cook rice|Microwave rice|Rice pouch, Basmati rice|Basmati, Jasmine rice|Thai rice, Risotto rice|Arborio,
      Pudding rice, Wild rice, Sushi rice, Couscous, Bulgur|Bulgur wheat, Quinoa, Lentils|Red lentils|Green lentils|Puy lentils|Beluga lentils, Polenta|Cornmeal|Grits,
      Mashed potato|Instant mash|Potato flakes, Dumplings, Glass noodles|Rice noodles|Rice vermicelli, Instant noodles|Ramen|Udon|Soba|Pot noodle,
      Millet, Pearl barley|Barley, Buckwheat, Orzo, Stuffing mix
    `,
    konserven: `
      Tomato puree|Tomato paste|Tomato purée, Passata|Sieved tomatoes, Chopped tomatoes|Tinned tomatoes|Canned tomatoes|Plum tomatoes tin|Crushed tomatoes|Diced tomatoes,
      Coconut milk|Coconut cream, Chickpeas|Garbanzo beans, Kidney beans|Red kidney beans, Cannellini beans|White beans|Butter beans|Haricot beans, Black beans, Baked beans|Pinto beans|Refried beans,
      Sweetcorn|Corn|Canned corn|Tinned sweetcorn, Tuna|Tinned tuna|Canned tuna|Tuna chunks, Sardines, Anchovies, Olives|Green olives|Black olives|Kalamata olives,
      Capers, Gherkins|Pickles|Cornichons|Dill pickles, Sauerkraut, Pickled red cabbage, Apple sauce|Applesauce, Fruit puree|Fruit pouches|Baby fruit pouches,
      Tinned fruit|Canned fruit|Canned peaches|Tinned pineapple|Fruit cocktail, Soup|Tinned soup|Canned soup|Packet soup, Pasta sauce|Tomato sauce|Arrabbiata sauce|Bolognese sauce|Marinara|Ragu,
      Pesto|Green pesto|Red pesto, Ketchup|Tomato ketchup, Mayonnaise|Mayo|Tartare sauce, Mustard|English mustard|Dijon mustard|Wholegrain mustard|Yellow mustard,
      BBQ sauce|Barbecue sauce, Soy sauce|Tamari|Shoyu, Curry paste|Red curry paste|Green curry paste|Curry sauce|Tikka masala sauce, Tahini|Tahina,
      Peanut sauce|Satay sauce, Sweet chilli sauce|Chilli sauce|Hot sauce, Sriracha, Tabasco, Fish sauce, Oyster sauce, Hoisin sauce, Teriyaki sauce,
      Sun-dried tomatoes|Sundried tomatoes, Artichoke hearts, Pickled beetroot, Chutney|Mango chutney|Pickle|Branston pickle, Ready meals|Tinned ravioli|Stew|Chili con carne tin,
      Salsa|Dip|Salsa dip, Canned mushrooms, Jackfruit, Horseradish|Horseradish sauce, Worcestershire sauce, Mint sauce, Cranberry sauce, Gravy|Gravy granules|Bisto,
      Brown sauce|HP sauce, Salad cream, Tinned peas|Mushy peas, Condensed soup, Spam
    `,
    oel: `
      Olive oil|Extra virgin olive oil|Virgin olive oil, Oil|Vegetable oil|Sunflower oil|Rapeseed oil|Canola oil|Cooking oil|Frying oil, Coconut oil, Sesame oil, Walnut oil|Linseed oil,
      Balsamic vinegar|Balsamic|Balsamic glaze, Vinegar|White wine vinegar|Red wine vinegar|Apple cider vinegar|Cider vinegar|Malt vinegar|Distilled vinegar, Lemon juice|Lime juice,
      Salt|Sea salt|Table salt|Rock salt|Flaky salt|Kosher salt, Pepper|Black pepper|Peppercorns|Ground pepper|White pepper, Spices|Spice|Seasoning,
      Paprika|Smoked paprika|Sweet paprika|Hot paprika, Curry powder, Turmeric|Ground turmeric, Cumin|Ground cumin|Cumin seeds, Caraway seeds,
      Cinnamon|Ground cinnamon|Cinnamon sticks, Nutmeg|Ground nutmeg, Oregano|Dried oregano, Chilli flakes|Chili flakes|Chilli powder|Chili powder|Cayenne pepper|Red pepper flakes,
      Garlic powder|Garlic granules|Onion powder, Mixed herbs|Italian seasoning|Herbes de Provence|Dried herbs, Bay leaves, Cloves, Garam masala, Ras el hanout,
      Za’atar|Zaatar, Sumac, Vanilla|Vanilla pod|Vanilla extract|Vanilla essence, Stock cubes|Stock|Vegetable stock|Bouillon|Broth|Vegetable broth, Chicken stock|Chicken broth,
      Beef stock|Beef broth|Fond, Salad dressing|Dressing|Vinaigrette|Ranch dressing, Mustard seeds, Nutritional yeast, BBQ seasoning|Steak seasoning|Cajun seasoning|Fajita seasoning|Taco seasoning,
      Herb salt|Celery salt, Ground ginger, Coriander seeds|Ground coriander, Allspice, Five spice, Dried thyme, Dried rosemary, Dried basil, Dried parsley
    `,
    backen: `
      Flour|Plain flour|All-purpose flour|Self-raising flour|Self-rising flour|Wheat flour, Strong bread flour|Bread flour, Wholemeal flour|Whole wheat flour|Rye flour|Spelt flour,
      Sugar|Caster sugar|Granulated sugar|White sugar, Brown sugar|Demerara sugar|Muscovado sugar|Cane sugar, Icing sugar|Powdered sugar|Confectioners sugar,
      Baking powder, Bicarbonate of soda|Baking soda|Bicarb, Yeast|Dried yeast|Fast action yeast|Fresh yeast, Vanilla sugar, Cornflour|Cornstarch|Corn starch|Starch,
      Cooking chocolate|Baking chocolate|Chocolate chips|Chocolate drops, Almonds|Ground almonds|Flaked almonds|Almond flour, Hazelnuts|Ground hazelnuts,
      Walnuts, Nuts|Mixed nuts, Cashews|Cashew nuts, Pine nuts, Sunflower seeds, Pumpkin seeds|Pepitas, Sesame seeds|Sesame,
      Raisins|Sultanas|Currants dried, Dates|Medjool dates, Dried fruit|Dried apricots|Dried mango|Dried cranberries|Cranberries|Prunes, Desiccated coconut|Coconut flakes|Shredded coconut,
      Gelatine|Gelatin|Agar agar, Breadcrumbs|Panko, Semolina, Sprinkles|Hundreds and thousands|Chocolate sprinkles, Cake mix|Brownie mix|Baking mix,
      Custard powder|Instant pudding, Glacé cherries, Marzipan, Food colouring|Food coloring, Pistachios, Pecans|Pecan nuts, Macadamia nuts, Brazil nuts,
      Condensed milk|Sweetened condensed milk, Evaporated milk, Treacle|Molasses
    `,
    suess: `
      Chocolate|Chocolate bar|Dark chocolate|Milk chocolate|White chocolate|Cadbury|Dairy Milk|Lindt|Milka, Biscuits|Cookies|Digestives|Shortbread|Hobnobs|Oreos|Cookie,
      Crisps|Chips|Potato chips|Potato crisps|Pringles|Walkers|Doritos, Tortilla chips|Nachos, Gummy bears|Sweets|Haribo|Jelly sweets|Gummies|Wine gums, Pretzel sticks|Pretzels snack,
      Crackers|Cream crackers|Ritz|Cheese crackers, Popcorn, Cereal bars|Granola bars|Protein bars|Snack bars|Chocolate bars|Snickers|Mars|KitKat|Twix, Candy|Lollipops|Mints,
      Chewing gum|Gum, Peanuts|Salted peanuts|Roasted peanuts, Trail mix|Nut mix|Student mix, Rice cakes|Corn cakes, Chocolates|Pralines|Ferrero Rocher|Box of chocolates,
      Gingerbread, Wafers|Waffles, Candy bars, Liquorice|Licorice, Kinder|Kinder chocolate, Salted nuts, Dried fruit snacks, Cake bars|Mini rolls|Flapjacks,
      Marshmallows, Jelly beans, Ice cream cones|Wafer cones
    `,
    pflanzendrink: `
      Oat milk|Oat drink|Oatly|Oat milk barista|Barista oat, Soy milk|Soya milk|Soy drink|Soya drink|Soy barista, Almond milk|Almond drink,
      Rice milk|Rice drink, Coconut drink|Coconut milk drink, Plant milk|Plant-based milk|Dairy-free milk|Non-dairy milk|Vegan milk, Pea milk, Cashew milk|Hazelnut milk,
      UHT milk|Long life milk|Long-life milk|Shelf-stable milk, Coffee creamer powder|Coffee whitener|Coffee-mate
    `,
    getraenke: `
      Water|Mineral water|Sparkling water|Still water|Bottled water|Soda water|Fizzy water, Juice|Orange juice|Apple juice|OJ|Multivitamin juice|Grape juice|Cranberry juice|Pineapple juice,
      Juice spritzer|Apple spritzer, Cola|Coca-Cola|Coke|Pepsi|Diet Coke|Coke Zero, Lemonade|Soft drinks|Fanta|Sprite|7up|Soda|Fizzy drinks|Cordial|Ribena,
      Iced tea|Ice tea, Beer|Lager|Ale|Bitter|Stout|Guinness|IPA|Pale ale|Wheat beer|Pilsner, Shandy|Radler, Alcohol-free beer|Non-alcoholic beer|Low alcohol beer,
      Wine|Red wine|White wine|Rosé|Rose wine, Sparkling wine|Prosecco|Champagne|Cava|Crémant, Gin, Vodka, Rum, Whisky|Whiskey|Bourbon|Scotch, Aperol|Campari|Liqueur,
      Tonic water|Tonic|Bitter lemon|Ginger ale|Ginger beer, Energy drink|Red Bull|Monster|Lucozade, Mate|Club Mate, Kombucha, Smoothie|Smoothies,
      Ginger shots|Shots, Elderflower cordial|Syrup, Malt drink, Sports drink|Isotonic drink|Gatorade|Powerade, Cider|Hard cider, Coconut water, Tomato juice
    `,
    tk: `
      Frozen pizza|Pizza|Stone baked pizza, Fries|French fries|Oven chips|Potato wedges|Hash browns|Potato croquettes|Tater tots,
      Fish fingers|Fish sticks|Battered fish|Breaded fish, Frozen vegetables|Frozen veg|Frozen spinach|Stir fry frozen|Mixed vegetables frozen, Peas|Frozen peas|Petits pois|Garden peas,
      Frozen berries|Frozen mixed berries|Frozen fruit|Frozen raspberries|Frozen blueberries, Frozen mango|Smoothie mix|Smoothie packs,
      Ice cream|Ice lollies|Popsicles|Magnum|Ben & Jerry’s|Ben and Jerrys|Häagen-Dazs|Sorbet|Gelato, Edamame, Chicken nuggets|Nuggets|Chicken dippers, Frozen herbs,
      Frozen bread|Frozen croissants, Spring rolls, Frozen lasagne|Frozen ready meals|Frozen meals, Ice cubes|Ice|Crushed ice,
      Frozen prawns|Frozen shrimp, Frozen puff pastry, Gyoza|Dim sum|Frozen dumplings, Yorkshire puddings, Frozen fish, Frozen chicken,
      Garlic bread, Frozen waffles|Frozen pancakes, Frozen sweetcorn
    `,
    drogerie: `
      Deodorant|Deo|Antiperspirant|Roll-on|Deodorant spray|Deodorant stick, Toothpaste|Colgate|Sensodyne|Aquafresh|Oral-B toothpaste|Crest,
      Toothbrush|Toothbrushes|Electric toothbrush heads|Brush heads, Dental floss|Floss|Interdental brushes|Toothpicks, Mouthwash|Listerine|Mouth rinse,
      Shower gel|Body wash|Shower cream, Shampoo, Conditioner|Hair conditioner, Hair mask|Hair treatment|Hair oil,
      Hair gel|Hairspray|Hair wax|Styling cream|Mousse, Soap|Liquid soap|Hand soap|Hand wash|Bar soap, Hand cream, Body lotion|Body cream|Moisturiser|Moisturizer,
      Face cream|Day cream|Night cream|Nivea|Face moisturiser, Sun cream|Suncream|Sunscreen|Sun lotion|SPF|After sun,
      Lip balm|Chapstick|Lip care, Razors|Razor blades|Disposable razors|Razor, Shaving foam|Shaving gel|Shaving cream, Aftershave|After shave,
      Cotton pads|Make-up pads|Makeup remover pads, Cotton buds|Q-tips|Cotton swabs, Cotton wool, Tissues|Kleenex|Paper tissues|Facial tissues,
      Toilet paper|Toilet roll|Toilet rolls|Loo roll|Bathroom tissue, Wet wipes|Baby wipes|Moist toilet tissue, Plasters|Band-aids|Bandaids|Blister plasters,
      Tampons|Sanitary pads|Pads|Panty liners|Feminine hygiene|Menstrual cup, Condoms, Nail file|Nail polish|Nail varnish|Nail polish remover|Nail clippers,
      Make-up|Makeup|Mascara|Lipstick|Powder|Concealer|Foundation|Eyeliner|Eyeshadow, Makeup remover|Micellar water|Toner|Cleanser|Face wash,
      Perfume|Eau de toilette|Cologne, Contact lens solution|Contact lenses|Saline solution, Vitamins|Supplements|Magnesium|Vitamin D|Zinc|Effervescent tablets|Multivitamins,
      Nappies|Diapers|Pampers|Huggies, Baby food|Baby puree|Baby jars, Hair ties|Hair clips|Hairbrush|Comb|Bobby pins, Foot cream|Blister cream,
      Painkillers|Paracetamol|Ibuprofen|Aspirin, Throat lozenges|Cough sweets|Cough drops|Nasal spray|Cold medicine, Earplugs, Scented candle, Intimate wash, Hand sanitiser|Hand sanitizer
    `,
    haushalt: `
      Washing up liquid|Dish soap|Fairy|Dishwashing liquid, Dishwasher tablets|Dishwasher tabs|Dishwasher pods|Finish|Dishwasher detergent,
      Rinse aid, Dishwasher salt, Laundry detergent|Washing powder|Washing liquid|Laundry liquid|Laundry pods|Persil|Ariel|Tide|Bold|Non-bio|Bio detergent,
      Fabric softener|Fabric conditioner|Comfort|Lenor|Downy, Stain remover|Vanish|Stain spray, All purpose cleaner|Cleaner|Multi-surface cleaner|Mr Muscle|Flash|Cleaning spray,
      Glass cleaner|Window cleaner|Windex, Bathroom cleaner|Limescale remover|Descaler, Kettle descaler|Coffee machine descaler, Toilet cleaner|Bleach|Toilet blocks|Domestos|Harpic,
      Sponges|Sponge|Scourers|Scrub sponge|Steel wool, Cloths|Cleaning cloths|Microfibre cloths|Dishcloths|J-cloths, Kitchen roll|Paper towels|Kitchen paper|Plenty|Bounty,
      Bin bags|Bin liners|Garbage bags|Trash bags|Rubbish bags|Food waste bags|Compost bags, Tin foil|Aluminium foil|Aluminum foil|Foil, Cling film|Plastic wrap|Cling wrap, Baking paper|Parchment paper|Greaseproof paper,
      Freezer bags|Zip lock bags|Ziploc|Sandwich bags|Food bags, Batteries|AA batteries|AAA batteries, Light bulbs|Light bulb|LED bulb, Candles|Tea lights, Matches|Lighter,
      Napkins|Serviettes, Paper plates|Disposable cups|Paper cups|Straws|Plastic cutlery, Charcoal|BBQ charcoal|Firelighters, Cat food|Dog food|Cat litter|Pet food|Pet treats|Dog treats,
      Compost|Potting soil|Plant food|Fertiliser|Fertilizer, Drain cleaner|Drain unblocker, Oven cleaner, Floor cleaner|Wood floor cleaner, Vinegar cleaner,
      Clothes pegs, Vacuum bags|Hoover bags, Rubber gloves|Gloves|Disposable gloves, Air freshener|Room spray|Febreze, Moth balls, Shoe polish, Dusters|Feather duster
    `,
    sonstiges: ``,
  },

  // Beispiele für den Verlauf beim ersten Öffnen, damit Vorschläge und Schnellauswahl gleich etwas anbieten
  start: ['Milk', 'Bread', 'Eggs', 'Butter', 'Bananas', 'Apples', 'Tomatoes', 'Cucumber', 'Onions', 'Potatoes', 'Cheddar', 'Yogurt',
    'Chicken breast', 'Mince', 'Pasta', 'Rice', 'Coffee', 'Tea', 'Orange juice', 'Toilet paper', 'Washing up liquid', 'Toothpaste',
    'Salmon', 'Carrots', 'Spinach', 'Oats', 'Chocolate', 'Crisps', 'Chopped tomatoes', 'Mozzarella'],

  // Typischer Vorrat: im Rezept-Prüfblatt standardmäßig abgewählt
  vorrat: ['Salt', 'Pepper', 'Black pepper', 'Oil', 'Olive oil', 'Vegetable oil', 'Flour', 'Sugar', 'Water', 'Vinegar', 'Cinnamon', 'Paprika',
    'Baking powder', 'Curry powder', 'Nutmeg', 'Oregano', 'Cornflour', 'Cornstarch', 'Vanilla extract', 'Vegetable stock', 'Stock cubes',
    'Chilli flakes', 'Cumin', 'Bay leaves', 'Baking soda', 'Bicarbonate of soda', 'Soy sauce'],
};
