// Sprachpaket Spanisch: Texte der Oberfläche, Artikelkatalog, Startverlauf und typischer Vorrat.
// Schlüssel der Texte ist der deutsche Text aus index.html; {0}, {1} … sind eingesetzte Werte.
// Katalog im selben Format wie katalog.js: Einträge durch Komma getrennt, Synonyme durch „|“, „~“ = Falschschreibung.
// Spanisch aus Spanien, dazu gängige lateinamerikanische Wörter als Synonyme (Papas, Jugo, Frutillas …).

(window.SPRACHPAKETE = window.SPRACHPAKETE || {}).es = {
  texte: {
    'Einkaufsliste': 'Lista de la compra',
    'Speichern fehlgeschlagen': 'No se pudo guardar',
    'Supermarkt': 'Supermercado',
    'Drogerie': 'Droguería',
    'Stück': 'uds.',
    '{0}: diesmal nicht': '{0}: esta vez no',
    'Rückgängig': 'Deshacer',
    '{0} gelöscht': 'Eliminado: {0}',
    'Auch die Stammartikel werden entfernt.': 'También se eliminarán los artículos habituales.',
    'Die ganze Einkaufsliste löschen ({0} Artikel)?': { one: '¿Borrar toda la lista de la compra ({0} artículo)?', other: '¿Borrar toda la lista de la compra ({0} artículos)?' },
    'Liste gelöscht': 'Lista borrada',
    'Einkauf abgeschlossen ({0})': 'Compra terminada ({0})',
    'Rezept · {0} Zutaten': { one: 'Receta · {0} ingrediente', other: 'Receta · {0} ingredientes' },
    'schon auf der Liste': 'ya está en la lista',
    'Korrektur': 'corrección',
    'zuordnen': 'asignar',
    'Diesmal nicht': 'Esta vez no',
    'Löschen': 'Eliminar',
    'Zurückholen': 'Recuperar',
    'Abhaken': 'Marcar',
    'Laden': 'Tienda',
    'Laden wählen': 'Elegir tienda',
    'Die Liste ist leer.': 'La lista está vacía.',
    'Oben eintragen, scannen oder ein Rezept übernehmen.': 'Escribe arriba, escanea o añade una receta.',
    'Nicht in diesem Laden ({0})': 'No hay en esta tienda ({0})',
    'Diesmal nicht:': 'Esta vez no:',
    'Ganze Liste löschen': 'Borrar toda la lista',
    'Einkauf abschließen · {0} erledigt': 'Terminar la compra · marcados: {0}',
    'Schnellauswahl': 'Selección rápida',
    'Schnellauswahl zeigen': 'Mostrar selección rápida',
    'Schnellauswahl ausblenden': 'Ocultar selección rápida',
    'Kein Rezept {0}': 'No hay receta {0}',
    'Noch keine Rezepte gespeichert': 'Aún no hay recetas guardadas',
    'Abbrechen': 'Cancelar',
    'Nicht mehr anheften': 'Desfijar',
    'Immer in der Schnellauswahl zeigen': 'Mostrar siempre en la selección rápida',
    'Nicht mehr vorschlagen': 'No volver a sugerir',
    'Verwalten unter Einstellungen → Schnellauswahl.': 'Gestiónalo en Ajustes → Selección rápida.',
    'Artikel': 'Artículo',
    'Fertig': 'Listo',
    'Name': 'Nombre',
    'Menge': 'Cantidad',
    'Weniger': 'Menos',
    'Mehr': 'Más',
    'Abteilung': 'Sección',
    'Marke / Notiz': 'Marca / nota',
    'z. B. Alnatura, 1,5 %': 'p. ej. ecológica, semidesnatada',
    'Wird immer benötigt': 'Siempre hace falta',
    'Steht nach jedem Einkauf von selbst wieder auf der Liste': 'Vuelve sola a la lista después de cada compra',
    'Von der Liste löschen': 'Eliminar de la lista',
    'Abteilung wählen. Die App merkt sich das für diesen Artikel.': 'Elige una sección. La app lo recordará para este artículo.',
    'Angeheftet, immer zuerst': 'Fijados, siempre primero',
    'Lösen': 'Desfijar',
    'Danach automatisch die häufigsten Käufe, ohne Stammartikel. Auch in der Schnellauswahl: Chip lange drücken.':
      'Después, tus compras más frecuentes, sin los artículos habituales. En la selección rápida también puedes mantener pulsado un chip.',
    'Anheften': 'Fijar',
    'Ausblenden': 'Ocultar',
    'Noch nichts gekauft.': 'Todavía no has comprado nada.',
    'Ausgeblendet': 'Ocultos',
    'Wieder zeigen': 'Mostrar de nuevo',
    'Automatisch ({0})': 'Automático ({0})',
    'Einstellungen': 'Ajustes',
    'Läden': 'Tiendas',
    'Standort gespeichert': 'ubicación guardada',
    '{0} Abteilungen': { one: '{0} sección', other: '{0} secciones' },
    'Laden hinzufügen': 'Añadir tienda',
    'Laden per Standort wählen': 'Elegir tienda por ubicación',
    'Beim Öffnen im Laden passendes Profil einstellen': 'Al abrir la app en una tienda, cambiar a esa tienda',
    'Sprache': 'Idioma',
    'Gilt für Texte, Abteilungen und die Erkennung der Artikel. Schon eingetragene Artikel behalten ihren Namen.':
      'Se aplica a los textos, las secciones y el reconocimiento de artículos. Los artículos que ya están en la lista conservan su nombre.',
    'Darstellung': 'Apariencia',
    'Automatisch': 'Automático',
    'Hell': 'Claro',
    'Dunkel': 'Oscuro',
    'Abteilungen farbig markieren': 'Marcar secciones con colores',
    'Farbe je Bereich im Laden, die Beschriftung bleibt': 'Un color por zona de la tienda, los nombres se mantienen',
    'Abteilung in der Listenansicht zeigen': 'Mostrar la sección en la lista',
    'Name der Abteilung rechts neben dem Artikel': 'Nombre de la sección a la derecha del artículo',
    'Streifen': 'Franjas',
    'Farbige Zeilen': 'Filas de color',
    'Nur in der Listenansicht, wenn das Eingabefeld leer ist': 'Solo en la lista, cuando el campo de texto está vacío',
    'Anzeigen': 'Mostrar',
    'Beim Antippen': 'Al tocar',
    'Immer': 'Siempre',
    'Immer unter dem Eingabefeld. Nach oben wischen blendet sie aus, antippen oder nach unten wischen holt sie zurück.':
      'Siempre debajo del campo de texto. Desliza hacia arriba para ocultarla; toca o desliza hacia abajo para que vuelva.',
    'Erscheint, sobald du ins Eingabefeld tippst, und bei leerer Liste.': 'Aparece en cuanto tocas el campo de texto y cuando la lista está vacía.',
    'Anzahl': 'Cantidad',
    'Artikel anheften': 'Fijar un artículo',
    'Stammartikel': 'Artículos habituales',
    'Entfernen': 'Quitar',
    'Noch keine. Artikel antippen und „Wird immer benötigt“ einschalten.': 'Ninguno. Toca un artículo y activa «Siempre hace falta».',
    'Rezepte': 'Recetas',
    '{0} Zutaten': { one: '{0} ingrediente', other: '{0} ingredientes' },
    'Noch keine. Beim Übernehmen eines Rezepts einen Namen vergeben, dann im Eingabefeld mit #Name abrufen.':
      'Ninguna. Ponle nombre a una receta al añadirla y luego llámala en el campo de texto con #Nombre.',
    'Rezept-Fotos': 'Fotos de recetas',
    'Claude-API-Schlüssel (bleibt nur auf diesem Gerät)': 'Clave API de Claude (solo se guarda en este dispositivo)',
    'Ohne Schlüssel funktioniert „Zutaten übernehmen“ per Text weiterhin. Mit Schlüssel kostet ein Rezeptfoto etwa 2–3 Cent.':
      'Sin clave, «Añadir ingredientes» sigue funcionando con texto pegado. Con clave, cada foto de receta cuesta unos 2–3 céntimos.',
    'Daten': 'Datos',
    'Sicherung exportieren': 'Exportar copia de seguridad',
    'Sicherung importieren': 'Importar copia de seguridad',
    'Verlauf und gelernte Zuordnungen löschen': 'Borrar historial y secciones aprendidas',
    '{0} Artikel im Verlauf · {1} gelernte Zuordnungen · {2} Katalogbegriffe': '{0} artículos en el historial · {1} secciones aprendidas · {2} términos del catálogo',
    'Neuer Laden': 'Tienda nueva',
    'Verlauf, gelernte Abteilungen und gespeicherte Barcodes löschen? Die aktuelle Liste bleibt.':
      '¿Borrar el historial, las secciones aprendidas y los códigos de barras guardados? La lista actual se mantiene.',
    'Zurück': 'Atrás',
    'z. B. REWE Hauptstraße': 'p. ej. Mercadona Calle Mayor',
    'Laufweg': 'Recorrido por la tienda',
    'Am Griff ziehen, um die Reihenfolge zu ändern. Haken entfernen, wenn es die Abteilung in diesem Laden nicht gibt.':
      'Arrastra el asa para cambiar el orden. Desmarca una sección si esta tienda no la tiene.',
    'In diesem Laden vorhanden': 'Hay en esta tienda',
    'Verschieben': 'Mover',
    'Standort': 'Ubicación',
    'Nicht gespeichert. Auf der Karte wählen oder im Laden stehend übernehmen, dann wählt die App diesen Laden automatisch.':
      'No guardada. Elígela en el mapa o guárdala estando en la tienda; así la app elegirá esta tienda automáticamente.',
    'Auf der Karte gewählt: {0}.': 'Elegida en el mapa: {0}.',
    'Auf der Karte gewählt.': 'Elegida en el mapa.',
    'Gespeichert (±{0} m).': 'Guardada (±{0} m).',
    'Auf der Karte wählen': 'Elegir en el mapa',
    'Aktuellen Standort übernehmen': 'Usar la ubicación actual',
    'Standort entfernen': 'Quitar ubicación',
    'Laden löschen': 'Eliminar tienda',
    'Standort wird bestimmt': 'Buscando ubicación',
    'Standort nicht verfügbar': 'Ubicación no disponible',
    '„{0}“ löschen?': '¿Eliminar «{0}»?',
    'Sicherung einspielen? Die aktuellen Daten werden ersetzt (der API-Schlüssel bleibt).':
      '¿Restaurar la copia? Los datos actuales se sustituirán (la clave API se mantiene).',
    'Sicherung eingespielt': 'Copia restaurada',
    'Datei konnte nicht gelesen werden': 'No se pudo leer el archivo',
    'Standort wählen': 'Elegir ubicación',
    'Adresse oder Markt suchen': 'Buscar dirección o tienda',
    'Karte wird geladen': 'Cargando mapa',
    'Standort übernehmen': 'Usar esta ubicación',
    'Die Karte konnte nicht geladen werden. Bitte Internetverbindung prüfen.': 'No se pudo cargar el mapa. Comprueba la conexión a internet.',
    'Namen übernehmen': 'Usar el nombre',
    'Nadel gesetzt. Tippe auf einen Markt-Punkt, um auch den Namen zu übernehmen.': 'Chincheta colocada. Toca el punto de una tienda para usar también su nombre.',
    'Zum Anzeigen der Märkte näher heranzoomen oder oben suchen.': 'Acerca el mapa para ver las tiendas o busca arriba.',
    'Märkte werden gesucht …': 'Buscando tiendas …',
    '1 Markt: Punkt antippen oder Nadel per Tippen auf die Karte setzen.': '1 tienda: toca el punto o toca el mapa para poner una chincheta.',
    '{0} Märkte: Punkt antippen oder Nadel per Tippen auf die Karte setzen.': '{0} tiendas: toca un punto o toca el mapa para poner una chincheta.',
    'Hier keine Märkte gefunden. Nadel per Tippen auf die Karte setzen.': 'No se encontraron tiendas aquí. Toca el mapa para poner una chincheta.',
    'Märkte gerade nicht abrufbar. Nadel per Tippen auf die Karte setzen.': 'Ahora no se pueden cargar las tiendas. Toca el mapa para poner una chincheta.',
    'Standort wird bestimmt …': 'Buscando ubicación …',
    'Adresse oder Markt oben suchen, oder die Karte verschieben und heranzoomen.': 'Busca una dirección o tienda arriba, o mueve el mapa y acércalo.',
    'Suche …': 'Buscando …',
    'Suche gerade nicht erreichbar': 'La búsqueda no está disponible ahora',
    'Nichts gefunden': 'No se encontró nada',
    'Standort gespeichert: {0}': 'Ubicación guardada: {0}',
    'Erst bei einem Laden den Standort speichern': 'Primero guarda la ubicación de una tienda',
    'Laden: {0}': 'Tienda: {0}',
    'Kein gespeicherter Laden in der Nähe': 'No hay ninguna tienda guardada cerca',
    'Nummer eingeben': 'Introducir número',
    'Barcode in den Rahmen halten': 'Coloca el código de barras dentro del marco',
    'EAN-Nummer (unter dem Barcode):': 'Número EAN (debajo del código de barras):',
    'Kamera nicht verfügbar. Zugriff in den Einstellungen erlauben oder Nummer eingeben.':
      'Cámara no disponible. Permite el acceso en Ajustes o introduce el número.',
    'Die Kamera geht nur, wenn die App über https geöffnet wird. Nummer eingeben geht trotzdem.':
      'La cámara solo funciona si la app se abre por https. Introducir el número funciona igualmente.',
    'Barcode {0}': 'Código de barras {0}',
    'Produkt wird gesucht': 'Buscando producto',
    'Schon einmal gescannt.': 'Ya escaneado antes.',
    'Gefunden. Name bei Bedarf kürzen.': 'Encontrado. Acorta el nombre si quieres.',
    'Nicht in der Produktdatenbank. Einmal benennen, dann merkt sich die App den Barcode.':
      'No está en la base de datos de productos. Ponle nombre una vez y la app recordará el código de barras.',
    'z. B. Alpro Haferdrink Barista 1 l': 'p. ej. Alpro bebida de avena 1 l',
    'Hinzufügen': 'Añadir',
    'auf der Liste': 'en la lista',
    'Vorrat': 'despensa',
    'Rezept übernehmen': 'Añadir receta',
    'Gespeicherte Rezepte': 'Recetas guardadas',
    'Im Foto oder Screenshot die Zutaten markieren (Text gedrückt halten), kopieren und hier einfügen.':
      'En una foto o captura de pantalla, selecciona los ingredientes (mantén pulsado el texto), cópialos y pégalos aquí.',
    'Zutaten': 'Ingredientes',
    '200 g Spaghetti&#10;2 Zehen Knoblauch&#10;1 Bund Basilikum': '200 g de espaguetis&#10;2 dientes de ajo&#10;1 manojo de albahaca',
    'Zutaten übernehmen': 'Añadir ingredientes',
    'Foto wählen und erkennen lassen': 'Elegir foto y reconocer',
    'Foto erkennen lassen (API-Schlüssel nötig)': 'Reconocer foto (hace falta clave API)',
    'Keine Zutaten erkannt': 'No se reconocieron ingredientes',
    'Foto wird ausgewertet': 'Analizando la foto',
    'Auf dem Foto wurden keine Zutaten gefunden.': 'No se encontraron ingredientes en la foto.',
    'Fehler bei der Erkennung.': 'Error en el reconocimiento.',
    'Was brauchst du?': '¿Qué necesitas?',
    'Abwählen, was noch im Vorrat ist. Name, Menge und Abteilung lassen sich antippen und ändern.':
      'Desmarca lo que ya tienes. Toca el nombre, la cantidad o la sección para cambiarlos.',
    'Übernehmen': 'Incluir',
    'Name und Menge': 'Nombre y cantidad',
    'Als Rezept speichern (optional, alle Zutaten)': 'Guardar como receta (opcional, todos los ingredientes)',
    'Name, z. B. Chili sin Carne': 'Nombre, p. ej. Chili sin carne',
    '1 Artikel hinzufügen': 'Añadir 1 artículo',
    '{0} Artikel hinzufügen': 'Añadir {0} artículos',
    '{0} und Rezept speichern': '{0} y guardar receta',
    'Nur Rezept speichern': 'Guardar solo la receta',
    'Rezept gespeichert, abrufen mit #{0}': 'Receta guardada, llámala con #{0}',
    'Es gibt schon ein Rezept „#{0}“. Ersetzen?': 'Ya existe una receta «#{0}». ¿Sustituirla?',
    'Name (abrufen mit #Name)': 'Nombre (llamar con #Nombre)',
    'Zutat, z. B. 500 g Hackfleisch': 'Ingrediente, p. ej. 500 g de carne picada',
    'Auf die Liste': 'Añadir a la lista',
    'Rezept löschen': 'Eliminar receta',
    '„#{0}“ gibt es schon': '«#{0}» ya existe',
    'Name fehlt': 'Falta el nombre',
    'Rezept „#{0}“ löschen?': '¿Eliminar la receta «#{0}»?',
    'API-Schlüssel ungültig. Bitte in den Einstellungen prüfen.': 'Clave API no válida. Revísala en Ajustes.',
    'Claude ist gerade ausgelastet. Bitte gleich noch einmal versuchen.': 'Claude está saturado ahora mismo. Vuelve a intentarlo en un momento.',
    'Fehler {0}': 'Error {0}',
    'Die Anfrage wurde abgelehnt. Bitte den Text einfügen.': 'La solicitud fue rechazada. Pega el texto en su lugar.',
    'Die Antwort war zu lang. Bitte einen kleineren Ausschnitt fotografieren.': 'La respuesta era demasiado larga. Fotografía una parte más pequeña.',
    'Keine offenen Artikel zum Teilen': 'No hay artículos pendientes para compartir',
    'Einkaufsliste ({0} Artikel)': { one: 'Lista de la compra ({0} artículo)', other: 'Lista de la compra ({0} artículos)' },
    'Zum Abhaken öffnen:': 'Abrir para marcar:',
    'Liste teilen': 'Compartir lista',
    'Teilen': 'Compartir',
    'Kopieren': 'Copiar',
    'Kopiert, jetzt in eine Nachricht einfügen': 'Copiado, ahora pégalo en un mensaje',
    'Der Link ist unvollständig oder beschädigt': 'El enlace está incompleto o dañado',
    'Der Link stammt aus einer neueren Version der App': 'El enlace procede de una versión más reciente de la app',
    'Es ist schon eine geteilte Liste mit abgehakten Artikeln offen. Durch die neue ersetzen?':
      'Ya hay abierta una lista compartida con artículos marcados. ¿Sustituirla por la nueva?',
    'geteilt am {0}': 'compartida el {0}',
    '{0} Artikel': { one: '{0} artículo', other: '{0} artículos' },
    'Die geteilte Liste ist leer.': 'La lista compartida está vacía.',
    'Erledigt zurückschicken · {0} von {1}': 'Devolver · marcados: {0} de {1}',
    'Geteilte Liste schließen? Die Häkchen gehen verloren. Schicke vorher die Rückmeldung, falls noch nicht geschehen.':
      '¿Cerrar la lista compartida? Se perderán las marcas. Envía antes la respuesta si aún no lo has hecho.',
    'Einkauf erledigt: {0} von {1} Artikeln': 'Compra hecha: {0} de {1} artículos',
    'Nicht bekommen:': 'No encontrado:',
    'In die Liste übernehmen:': 'Aplicar a la lista:',
    'Rückmeldung schicken': 'Enviar respuesta',
    'Rückmeldung': 'Respuesta',
    '{0} gekauft, {1} nicht bekommen.': 'Comprados: {0}. No encontrados: {1}.',
    'Gekauft': 'Comprado',
    'Nicht bekommen (bleibt offen)': 'No encontrado (sigue pendiente)',
    '1 Artikel steht nicht mehr auf dieser Liste.': '1 artículo ya no está en esta lista.',
    '{0} Artikel stehen nicht mehr auf dieser Liste.': '{0} artículos ya no están en esta lista.',
    'Nutzt du die App vom Home-Bildschirm? Dann kopiere den Link aus der Nachricht und füge ihn dort ins Eingabefeld ein. Safari und die App haben getrennte Listen.':
      '¿Usas la app desde la pantalla de inicio? Entonces copia el enlace del mensaje y pégalo allí en el campo de texto. Safari y la app tienen listas separadas.',
    '{0} als gekauft abhaken': { one: 'Marcar {0} como comprado', other: 'Marcar {0} como comprados' },
    'Nichts abzuhaken': 'Nada que marcar',
    '{0} abgehakt': 'Marcados: {0}',
    // Abteilungen
    'Gemüse': 'Verduras',
    'Obst': 'Fruta',
    'Brot & Backwaren': 'Pan y bollería',
    'Molkerei & Eier': 'Lácteos y huevos',
    'Käse': 'Quesos',
    'Fleisch & Wurst': 'Carne y embutidos',
    'Fisch': 'Pescado',
    'Tofu, Frischteig & Feinkost': 'Tofu, masas frescas y platos preparados',
    'Frühstück, Kaffee & Tee': 'Desayuno, café y té',
    'Nudeln, Reis & Beilagen': 'Pasta, arroz y legumbres',
    'Konserven & Saucen': 'Conservas y salsas',
    'Öl, Essig & Gewürze': 'Aceite, vinagre y especias',
    'Backzutaten & Nüsse': 'Repostería y frutos secos',
    'Süßes & Snacks': 'Dulces y aperitivos',
    'H-Milch & Pflanzendrinks': 'Leche UHT y bebidas vegetales',
    'Getränke': 'Bebidas',
    'Tiefkühl': 'Congelados',
    'Drogerie & Körperpflege': 'Higiene y cuidado personal',
    'Haushalt & Putzen': 'Hogar y limpieza',
    'Sonstiges': 'Otros',
    // Bereiche und Farbschemata
    'Obst & Gemüse': 'Frutas y verduras',
    'Brot': 'Pan',
    'Kühlregal': 'Refrigerados',
    'Fleisch & Fisch': 'Carne y pescado',
    'Trockenwaren': 'Alimentación seca',
    'Drogerie & Haushalt': 'Higiene y hogar',
    'Markt': 'Mercado',
    'Farben passend zur Ware: Gemüse grün, Brot gelb, Kühlregal blau, Fleisch rot.': 'Colores según el producto: verduras en verde, pan en amarillo, refrigerados en azul, carne en rojo.',
    'Kontrast': 'Contraste',
    'Größtmöglicher Abstand zwischen benachbarten Bereichen, auch bei Rot-Grün-Schwäche.': 'Máxima diferencia entre zonas vecinas, también con daltonismo rojo-verde.',
    'Ruhig': 'Discreto',
    'Nur vier Farben für die großen Zonen: Frisch, Kühlung, Trocken, Drogerie.': 'Solo cuatro colores para las zonas principales: fresco, refrigerado, seco, higiene.',
    'Frisch': 'Fresco',
    'Kühlung': 'Refrigerado',
    'Trocken & Getränke': 'Seco y bebidas',
    // Feste Texte im HTML
    'Liste': 'Lista',
    'Geteilte Liste': 'Lista compartida',
    'Schließen': 'Cerrar',
    'Artikel hinzufügen': 'Añadir artículo',
    'Barcode scannen': 'Escanear código de barras',
    'Einkauf abschließen': 'Terminar la compra',
  },

  katalog: {
    gemuese: `
      Tomates|Tomate|Tomates en rama|Tomate pera|Tomate de ensalada|Jitomate|Jitomates, Tomates cherry|Tomate cherry|Tomates cherri|Cherrys,
      Pepino|Pepinos|Mini pepinos, Calabacín|Calabacines|Calabacin|Zucchini, Pimientos|Pimiento|Pimiento rojo|Pimiento verde|Pimiento amarillo|Morrones|Pimientos de Padrón|Pimientos italianos,
      Zanahorias|Zanahoria, Patatas|Patata|Papas|Papa|Patatas nuevas|Patatas para freír|Patatas para cocer, Batatas|Boniatos|Batata|Boniato|Camote,
      Cebollas|Cebolla|Cebolla morada|Cebolla roja|Chalotas|Chalota|Escalonias, Cebolletas|Cebolleta|Cebollino tierno|Cebollas de verdeo, Ajo|Ajos|Cabeza de ajo|Dientes de ajo,
      Jengibre|Jengibre fresco, Cúrcuma fresca, Brócoli|Brocoli|Brécol|~Brocolí, Coliflor, Romanesco, Champiñones|Champiñón|Setas|Hongos|Champiñones laminados,
      Setas de ostra|Gírgolas, Shiitake, Rebozuelos, Lechuga|Ensalada|Mezclum|Brotes tiernos|Bolsa de ensalada|Ensalada mixta,
      Lechuga iceberg|Iceberg, Lechuga romana|Romana|Cogollos|Cogollos de Tudela, Canónigos, Rúcula|Rucula|Rúcola,
      Endivias|Endivia|Achicoria, Radicchio|Achicoria roja, Espinacas|Espinaca|Espinacas baby|Brotes de espinaca, Puerros|Puerro, Apio|Rama de apio,
      Apionabo|Raíz de apio, Verduras para caldo|Verduras para sopa, Berenjenas|Berenjena, Calabaza|Calabaza butternut|Zapallo|Auyama,
      Remolacha|Remolacha cocida|Betabel, Rábanos|Rabanitos|Rábano, Nabo daikon|Daikon, Colinabo, Repollo|Col|Col blanca, Lombarda|Col lombarda|Repollo morado, Col rizada|Col de Milán|Berza,
      Coles de Bruselas|Repollitos de Bruselas, Kale|Col kale, Col china, Pak choi|Bok choy, Hinojo, Espárragos|Espárragos verdes|Trigueros|Espárragos blancos,
      Mazorcas de maíz|Maíz dulce en mazorca|Choclo|Elote, Tirabeques|Guisantes lágrima|Arvejas chinas, Judías verdes|Judías|Vainas|Ejotes|Chauchas|Habichuelas,
      Aguacates|Aguacate|Palta|Paltas, Acelgas|Acelga, Chirivías|Chirivía, Tupinambo, Alcachofas|Alcachofa|Alcaucil, Okra|Quimbombó, Nabos|Nabo,
      Guindillas|Guindilla|Chiles|Chile|Ají|Jalapeños, Hierbas frescas|Hierbas aromáticas, Albahaca, Perejil|Perejil fresco,
      Cebollino, Cilantro|Culantro, Eneldo, Hierbabuena|Menta|Menta fresca, Romero, Tomillo, Salvia, Hierba limón|Limoncillo, Berros, Brotes|Brotes de soja|Germinados,
      Verduras|Verdura|Verduras frescas|Hortalizas, Salteado de verduras|Verduras para wok, Verduras para ensalada
    `,
    obst: `
      Manzanas|Manzana|Manzana golden|Pink Lady|Gala|Granny Smith|Manzana reineta, Plátanos|Plátano|Bananas|Banana|Banano|Guineo, Peras|Pera|Pera conferencia, Naranjas|Naranja|Naranjas de zumo, Mandarinas|Clementinas|Mandarina|Clementina,
      Limones|Limón|Limon, Limas|Lima, Pomelo|Pomelos|Toronja, Uvas|Uva|Uva blanca|Uva negra|Uvas sin pepitas, Fresas|Fresa|Frutillas|Frutilla|Fresones,
      Frambuesas|Frambuesa, Arándanos|Arándano|Arandanos, Moras|Mora|Zarzamoras, Grosellas|Grosella negra|Casis, Uva espina,
      Frutos rojos|Frutos del bosque|Bayas, Cerezas|Cereza|Picotas, Melocotones|Melocotón|Duraznos|Durazno|Paraguayos, Nectarinas|Nectarina, Albaricoques|Albaricoque|Damascos|Chabacanos,
      Ciruelas|Ciruela, Kiwis|Kiwi, Mangos|Mango, Piña|Piñas|Ananá, Melón|Sandía|Melón piel de sapo|Melón cantalupo|Patilla,
      Granada|Granadas, Higos|Higo|Brevas, Maracuyá|Fruta de la pasión, Papaya, Physalis|Uchuvas, Caquis|Caqui|Kakis|Persimón, Ruibarbo, Fruta|Fruta fresca, Lichis|Lichi,
      Coco, Membrillos|Membrillo fruta, Chirimoyas|Chirimoya, Nísperos
    `,
    brot: `
      Pan|Barra de pan|Pan integral|Pan de centeno|Pan de pueblo|Pan de hogaza|Hogaza|Pan con semillas|Pan de masa madre|Chapata, Pan de molde|Pan bimbo|Pan de molde integral|Pan tostado,
      Panecillos|Panecillo|Bollos de pan|Pan de leche|Bocadillos pan, Pretzels|Bretzel, Baguette|Baguettes|Barra, Ciabatta, Cruasanes|Cruasán|Croissants|Croissant|Napolitanas|Medialunas,
      Picos|Regañás|Colines|Tostas|Biscotes, Pan de pita|Pita|Pan naan|Naan, Pumpernickel, Pan precocido|Barras precocidas,
      Pan de hamburguesa|Panes de hamburguesa|Pan para hamburguesas, Pan de perrito|Pan para perritos, Bizcocho|Pastel|Tarta, Tortillas de trigo|Wraps|Tortillas mexicanas|Fajitas pan,
      Bagels|Bagel, Magdalenas|Muffins, Donuts|Rosquillas, Brioche|Suizos|Ensaimadas, Bollería|Bollos, Churros|Porras, Palmeras, Pan rallado fresco
    `,
    molkerei: `
      Leche|Leche entera|Leche semidesnatada|Leche desnatada|Leche fresca|Semidesnatada|Desnatada|Leche sin lactosa, Yogur|Yogures|Yogurt|Yoghurt|Yogur natural|Yogures de sabores|~Yougur,
      Yogur griego|Yogures griegos, Skyr, Queso fresco batido|Quark, Nata|Nata para montar|Nata para cocinar|Crema de leche|Crema|Nata montada,
      Nata agria|Crema agria, Crème fraîche, Mantequilla|Manteca|Mantequilla con sal|Mantequilla sin sal, Mantequilla de hierbas,
      Margarina|Tulipán, Huevos|Huevo|Huevos camperos|Huevos ecológicos|Docena de huevos, Suero de leche|Buttermilk, Kéfir|Kefir, Yogur líquido|Yogur para beber|Actimel,
      Natillas|Flan|Petit suisse|Arroz con leche|Cuajada|Postres lácteos|Mousse de chocolate, Tzatziki, Batido|Batido de chocolate|Cacaolat|Leche con cacao, Café frío|Café con leche frío,
      Postres|Postre, Leche condensada fresca
    `,
    kaese: `
      Queso|Queso en lonchas|Lonchas de queso|Queso loncheado, Queso manchego|Manchego|Queso curado|Queso semicurado|Queso tierno, Gouda, Emmental, Edam|Bola, Havarti|Tranchetes,
      Queso rallado|Rallado|Queso para pizza|Queso para gratinar, Parmesano|Parmigiano|Grana Padano, Pecorino, Mozzarella|Mozzarella de búfala|Mini mozzarella|Muzzarella,
      Burrata, Feta|Queso feta, Halloumi, Queso crema|Philadelphia|Queso untable|Queso de untar, Requesón|Queso cottage, Mascarpone, Ricotta,
      Camembert, Brie, Queso de cabra|Rulo de cabra, Queso azul|Cabrales|Roquefort|Gorgonzola, Queso para raclette|Raclette, Idiazábal|Tetilla|Torta del Casar|Mahón,
      Cheddar, Queso fresco|Queso de Burgos|Queso blanco, Gruyer|Gruyère|Comté, Provolone, Queso Oaxaca|Queso Chihuahua
    `,
    fleisch: `
      Carne picada|Picada|Carne molida|Molida|Picada de ternera|Picada mixta|Carne picada de cerdo, Pechuga de pollo|Pechugas de pollo|Filetes de pollo|Pechuga fileteada|Pechuga,
      Pollo|Pollo entero|Pollo asado|Muslos de pollo|Contramuslos|Alitas de pollo|Alitas|Jamoncitos de pollo, Pavo|Pechuga de pavo|Filetes de pavo|Carne de pavo,
      Escalope|Escalopes|Filetes empanados|Milanesas|Milanesa, Filete|Filetes|Bistec|Entrecot|Solomillo|Chuletón|Lomo alto|Bife, Ternera|Carne de ternera|Carne para guisar|Ternera para estofado|Redondo|Carne de res,
      Cerdo|Lomo de cerdo|Chuletas de cerdo|Solomillo de cerdo|Costillas|Panceta|Secreto ibérico|Presa ibérica|Carrillada, Cordero|Chuletas de cordero|Pierna de cordero|Paletilla de cordero,
      Albóndigas, Hamburguesas|Hamburguesa, Salchichas|Salchicha|Salchichas frescas|Longaniza|Butifarra, Salchichas de Frankfurt|Frankfurt|Perritos|Salchichas cocidas|Vienesas,
      Salami|Salchichón|Fuet|Pepperoni, Jamón cocido|Jamón york|Jamón dulce|Fiambre de jamón, Jamón serrano|Jamón ibérico|Jamón curado|Prosciutto,
      Bacon|Beicon|Tocino|Panceta ahumada|Taquitos de jamón|Tacos de bacon, Embutido|Embutidos|Fiambres|Fiambre, Paté|Foie gras|Paté de hígado,
      Mortadela|Chopped, Chorizo|Chorizo ibérico|Chorizo para cocinar, Morcilla, Pato|Magret de pato|Confit de pato, Carne de kebab|Gyros|Shawarma, Conejo, Hígado,
      Pinchos morunos|Brochetas, Lomo embuchado|Cecina, Carne
    `,
    fisch: `
      Salmón|Salmon|Lomos de salmón|Filete de salmón, Salmón ahumado, Trucha|Filetes de trucha, Trucha ahumada, Merluza|Bacalao|Abadejo|Pescado blanco|Filetes de pescado|Lomos de merluza|Pescadilla|Rape,
      Gambas|Langostinos|Camarones|Gambas peladas|Gambones|Quisquillas, Arenque|Arenques|Boquerones en vinagre, Caballa|Caballa ahumada|Jurel,
      Dorada|Lubina|Besugo|Lenguado|Gallo|Rodaballo, Calamares|Chipirones|Sepia|Pulpo|Choco, Mejillones|Almejas|Berberechos|Vieiras|Ostras|Navajas,
      Palitos de cangrejo|Surimi|Gulas, Cangrejo|Buey de mar, Pescado, Atún fresco|Bonito|Filete de atún, Sardinas frescas|Boquerones, Pez espada|Emperador, Bogavante|Langosta|Cigalas
    `,
    kuehlveg: `
      Tofu|Tofu ahumado|Tofu sedoso|Tofu firme, Tempeh, Seitán|Seitan, Hamburguesas vegetales|Hamburguesa vegana|Burger vegetal|Salchichas veganas|Salchichas vegetales|Carne picada vegetal|Heura,
      Falafel, Hummus|Humus, Ñoquis|Gnocchi|Noquis, Pasta fresca|Tortellini|Raviolis|Ravioli|Pasta rellena, Masa de pizza|Base de pizza, Hojaldre|Masa de hojaldre, Masa quebrada|Masa brisa,
      Pasta filo|Masa filo, Masa de croissant, Obleas de empanadilla|Tapas de empanada|Masa de empanadillas, Untables|Crema para untar|Paté vegetal,
      Antipasti|Aceitunas aliñadas|Encurtidos frescos, Pesto fresco, Kimchi, Ensaladilla rusa|Ensalada preparada|Ensalada de pasta|Tabulé,
      Sándwiches|Sandwiches|Wraps preparados, Tortilla de patatas|Tortilla española, Gazpacho|Salmorejo, Platos preparados|Comida preparada|Sopa fresca, Guacamole
    `,
    fruehstueck: `
      Copos de avena|Avena|Porridge|Gachas de avena, Muesli|Granola|Muesli crujiente|Muesli con frutas, Cereales|Corn flakes|Cereales de desayuno|Special K|Choco Krispies|Kellogg's,
      Nutella|Crema de cacao|Nocilla|Crema de avellanas, Mermelada|Confitura|Mermelada de fresa|Mermelada de melocotón|Dulce de membrillo|Membrillo, Miel, Crema de cacahuete|Mantequilla de maní|Mantequilla de cacahuete,
      Crema de almendras|Crema de frutos secos|Crema de anacardos, Café|Café en grano|Café molido|Espresso|Café de filtro, Cápsulas de café|Cápsulas|Nespresso|Dolce Gusto|Monodosis de café,
      Café soluble|Nescafé|Café instantáneo, Filtros de café, Té|Té negro|Bolsitas de té|Infusión|Infusiones|Tisana|Té de frutas|Poleo menta, Té verde, Té de menta|Menta poleo, Manzanilla, Té de jengibre, Chai,
      Cacao en polvo|Cola Cao|ColaCao|Nesquik|Chocolate a la taza|Cacao, Semillas de chía|Chía|Chia, Semillas de lino|Linaza, Proteína en polvo|Whey, Sirope de arce|Sirope de agave|Jarabe de arce,
      Mezcla para tortitas|Tortitas|Panqueques, Ovomaltina, Galletas de desayuno|Galletas María
    `,
    nudeln: `
      Espaguetis|Espagueti|Spaghetti|Tallarines|~Espagueties, Pasta|Pasta seca|Fideos, Macarrones|Macarrón|Penne, Fusilli|Hélices|Espirales, Lazos|Farfalle, Rigatoni, Tagliatelle|Tallarines al huevo|Pappardelle|Fettuccine,
      Linguine, Coditos, Placas de lasaña|Láminas de lasaña|Lasaña placas|Canelones, Pasta integral, Fideos de huevo|Fideos finos|Fideos para sopa|Fideuá,
      Arroz|Arroz redondo|Arroz largo|Arroz blanco|Arroz integral|Arroz vaporizado|Arroz bomba|Arroz para paella, Arroz basmati|Basmati, Arroz jazmín|Arroz thai, Arroz para risotto|Arborio,
      Arroz salvaje, Arroz para sushi, Cuscús|Couscous, Bulgur, Quinoa|Quinua, Lentejas|Lentejas rojas|Lentejas pardinas|Lentejas beluga, Garbanzos secos|Alubias secas|Judías secas|Frijoles secos|Legumbres, Polenta|Harina de maíz precocida,
      Puré de patatas|Puré instantáneo|Copos de puré, Fideos de arroz|Tallarines de arroz|Fideos chinos|Fideos de cristal, Fideos instantáneos|Ramen|Udon|Soba|Yatekomo,
      Mijo, Cebada perlada|Cebada, Trigo sarraceno|Alforfón, Orzo|Piñones pasta, Tapioca, Harina PAN|Masa de arepas
    `,
    konserven: `
      Tomate concentrado|Concentrado de tomate|Pasta de tomate, Tomate frito|Salsa de tomate frito, Tomate triturado|Tomates triturados|Tomate natural|Tomate en conserva|Tomates pelados|Tomate troceado,
      Leche de coco|Crema de coco, Garbanzos|Garbanzos cocidos|Bote de garbanzos, Alubias rojas|Judías rojas|Frijoles rojos, Alubias blancas|Judías blancas|Alubias cocidas, Frijoles negros|Alubias negras, Alubias con tomate|Baked beans,
      Maíz|Maíz dulce|Maíz en lata, Atún|Atún en lata|Atún en aceite|Atún claro|Lata de atún|Bonito del norte, Sardinas|Sardinas en lata|Sardinillas, Anchoas, Aceitunas|Aceitunas verdes|Aceitunas negras|Aceitunas rellenas|Olivas,
      Alcaparras, Pepinillos|Encurtidos|Banderillas, Chucrut, Lombarda en conserva, Compota de manzana|Compota|Puré de manzana, Bolsitas de fruta|Pouches de fruta|Purés de fruta,
      Fruta en almíbar|Melocotón en almíbar|Piña en almíbar|Macedonia en lata, Sopa|Sopa de sobre|Caldo en brik|Crema de verduras brik, Salsa para pasta|Salsa boloñesa|Salsa arrabbiata|Salsa napolitana,
      Pesto|Pesto verde|Pesto rojo, Kétchup|Ketchup, Mayonesa|Mahonesa|Salsa tártara|Alioli|Ajoaceite, Mostaza|Mostaza de Dijon|Mostaza antigua,
      Salsa barbacoa|Salsa BBQ, Salsa de soja|Salsa soya|Tamari|Shoyu, Pasta de curry|Curry rojo|Curry verde|Salsa de curry, Tahini|Tahina|Pasta de sésamo,
      Salsa de cacahuete|Salsa satay, Salsa de chile dulce|Salsa picante|Salsa de chile|Tabasco|Valentina, Sriracha, Salsa de pescado, Salsa de ostras, Salsa hoisin, Salsa teriyaki,
      Tomates secos, Corazones de alcachofa|Alcachofas en conserva, Remolacha en conserva, Chutney|Chutney de mango, Platos preparados en lata|Fabada|Cocido en lata|Lentejas preparadas|Raviolis en lata,
      Salsa mexicana|Dip|Pico de gallo, Champiñones en lata|Champiñón laminado en conserva, Yaca|Jackfruit, Rábano picante, Salsa Worcestershire|Salsa Perrins, Guisantes en lata|Menestra en conserva,
      Pimientos del piquillo|Pimientos asados|Pimiento morrón en lata, Espárragos en lata|Espárragos blancos en conserva, Mejillones en escabeche|Berberechos en lata|Conservas de pescado, Chiles en vinagre|Chipotles
    `,
    oel: `
      Aceite de oliva|Aceite de oliva virgen extra|AOVE|Aceite de oliva suave, Aceite|Aceite de girasol|Aceite vegetal|Aceite de semillas|Aceite para freír, Aceite de coco, Aceite de sésamo, Aceite de nuez|Aceite de linaza,
      Vinagre balsámico|Balsámico|Crema de balsámico|Reducción de Módena, Vinagre|Vinagre de vino|Vinagre de manzana|Vinagre blanco|Vinagre de Jerez|Vinagre de sidra, Zumo de limón|Jugo de limón|Zumo de lima,
      Sal|Sal fina|Sal gorda|Sal marina|Escamas de sal|Sal yodada, Pimienta|Pimienta negra|Pimienta en grano|Pimienta molida|Pimienta blanca, Especias|Especia|Condimentos|Sazonador,
      Pimentón|Pimentón dulce|Pimentón picante|Pimentón de la Vera|Paprika, Curry|Curry en polvo, Cúrcuma|Cúrcuma en polvo, Comino|Comino molido, Alcaravea,
      Canela|Canela molida|Canela en rama, Nuez moscada, Orégano|Orégano seco, Guindilla seca|Cayena|Chile en polvo|Copos de chile|Ají molido,
      Ajo en polvo|Ajo granulado|Cebolla en polvo, Hierbas provenzales|Finas hierbas|Hierbas italianas|Hierbas secas, Laurel|Hojas de laurel, Clavo|Clavos de olor, Garam masala, Ras el hanout,
      Zaatar, Zumaque, Vainilla|Vaina de vainilla|Extracto de vainilla|Esencia de vainilla, Caldo de verduras|Pastillas de caldo|Avecrem|Caldo en pastillas|Cubitos de caldo|Caldo, Caldo de pollo, Caldo de carne|Fondo,
      Aliño para ensalada|Vinagreta|Aderezo, Semillas de mostaza, Levadura nutricional, Especias para barbacoa|Sazonador para carne|Especias cajún|Especias para fajitas|Sazonador para tacos,
      Sal de hierbas|Sal de apio, Jengibre molido, Cilantro molido|Semillas de cilantro, Pimienta de Jamaica, Cinco especias, Tomillo seco, Perejil seco, Azafrán|Colorante alimentario amarillo
    `,
    backen: `
      Harina|Harina de trigo|Harina común|Harina de todo uso, Harina de fuerza|Harina panificable, Harina integral|Harina de centeno|Harina de espelta|Harina de avena,
      Azúcar|Azucar|Azúcar blanco|Azúcar blanquilla|Azúcar en terrones, Azúcar moreno|Azúcar de caña|Panela|Azúcar mascabado, Azúcar glas|Azúcar glass|Azúcar impalpable|Azúcar en polvo,
      Levadura química|Polvo de hornear|Levadura Royal|Polvos de hornear, Bicarbonato|Bicarbonato sódico|Bicarbonato de sodio, Levadura de panadería|Levadura seca|Levadura fresca, Azúcar avainillado, Maicena|Harina de maíz|Almidón de maíz|Fécula|Almidón,
      Chocolate para fundir|Chocolate de cobertura|Pepitas de chocolate|Chips de chocolate, Almendras|Almendra molida|Almendras laminadas|Harina de almendra, Avellanas|Avellana molida,
      Nueces|Nueces peladas, Frutos secos|Mezcla de frutos secos, Anacardos|Castañas de cajú|Merey, Piñones, Pipas de girasol|Semillas de girasol, Pipas de calabaza|Semillas de calabaza, Sésamo|Semillas de sésamo|Ajonjolí,
      Pasas|Uvas pasas, Dátiles|Dátiles Medjool, Orejones|Albaricoques secos|Mango deshidratado|Arándanos secos|Ciruelas pasas|Higos secos, Coco rallado,
      Gelatina|Hojas de gelatina|Gelatina neutra|Agar agar, Pan rallado|Panko, Sémola|Sémola de trigo, Fideos de colores|Virutas de chocolate|Sprinkles, Preparado para bizcocho|Preparado para brownie,
      Natillas en polvo|Flan en polvo|Preparado para flan, Cobertura para tartas, Mazapán, Colorante alimentario, Pistachos, Nueces pecanas, Nueces de macadamia, Nueces de Brasil,
      Leche condensada|Leche condensada azucarada, Leche evaporada, Dulce de leche|Cajeta, Frutas confitadas|Guindas, Aromas|Agua de azahar
    `,
    suess: `
      Chocolate|Tableta de chocolate|Chocolate negro|Chocolate con leche|Chocolate blanco|Milka|Lindt|Valor|Nestlé, Galletas|Galleta|Galletas María|Cookies|Oreo|Príncipe|Digestive,
      Patatas fritas|Patatas fritas de bolsa|Papas fritas|Chips|Pringles|Lays|Ruffles, Nachos|Tortilla chips|Totopos, Gominolas|Chuches|Golosinas|Haribo|Ositos de goma|Caramelos de goma, Pretzels de aperitivo|Palitos salados|Bastoncitos salados,
      Crackers|Galletas saladas|Tuc|Galletitas saladas, Palomitas|Palomitas de maíz|Pochoclo|Cotufas, Barritas de cereales|Barritas|Barritas de proteínas|Chocolatinas|Snickers|Mars|Twix|KitKat|Kinder Bueno, Caramelos|Piruletas|Chupa Chups|Pastillas de menta,
      Chicles|Chicle|Trident, Cacahuetes|Maní|Cacahuetes tostados|Cacahuetes salados, Frutos secos variados|Cóctel de frutos secos|Mix de frutos secos, Tortitas de arroz|Tortitas de maíz, Bombones|Ferrero Rocher|Caja de bombones,
      Turrón|Polvorones|Mantecados, Gofres|Barquillos|Obleas, Dulces|Golosinas variadas, Regaliz, Kinder|Huevo Kinder, Pipas|Pipas saladas|Almendras saladas, Aperitivos|Snacks|Gusanitos|Cheetos,
      Nubes|Malvaviscos|Marshmallows, Cucuruchos|Conos de helado, Bizcochos envasados|Magdalenas envasadas|Bollos envasados|Donettes|Pantera Rosa
    `,
    pflanzendrink: `
      Leche de avena|Bebida de avena|Oatly|Avena barista, Leche de soja|Bebida de soja|Soja barista, Leche de almendras|Bebida de almendras|Leche de almendra,
      Leche de arroz|Bebida de arroz, Bebida de coco|Leche de coco para beber, Bebida vegetal|Leche vegetal|Bebidas vegetales, Bebida de guisantes, Bebida de anacardos|Bebida de avellanas|Leche de avellanas,
      Leche UHT|Leche de larga duración|Brik de leche|Leche en brik, Leche en polvo, Crema para café|Blanqueador de café|Coffee Mate
    `,
    getraenke: `
      Agua|Agua mineral|Agua con gas|Agua sin gas|Agua embotellada|Garrafa de agua|Botellas de agua|Soda|Font Vella|Bezoya|Solán de Cabras, Zumo|Zumo de naranja|Zumo de manzana|Jugo|Jugo de naranja|Zumo multifrutas|Zumo de piña|Zumo de uva|Néctar|Zumo de tomate,
      Mosto|Refresco de zumo, Cola|Coca-Cola|Coca Cola|Pepsi|Coca-Cola Zero|Coca Zero, Refrescos|Refresco|Fanta|Fanta naranja|Fanta limón|Sprite|Seven Up|Gaseosa|Casera|Kas|Aquarius,
      Té frío|Nestea|Ice tea|Té helado, Cerveza|Cervezas|Caña|Lata de cerveza|Tercio|Cerveza rubia|Cerveza negra|Mahou|Estrella Galicia|Cruzcampo|San Miguel, Clara|Cerveza con limón|Radler, Cerveza sin alcohol|Cerveza 0,0,
      Vino|Vino tinto|Vino blanco|Rosado|Vino rosado|Rioja|Ribera|Albariño|Verdejo, Cava|Champán|Champagne|Vino espumoso|Prosecco, Ginebra|Gin, Vodka, Ron, Whisky|Whiskey|Bourbon, Vermut|Aperol|Campari|Licor|Pacharán|Sangría|Tinto de verano,
      Tónica|Agua tónica|Schweppes|Bitter Kas|Ginger ale|Ginger beer, Bebida energética|Red Bull|Monster|Burn, Mate|Club Mate|Yerba mate, Kombucha, Smoothie|Smoothies,
      Shots de jengibre|Shots, Sirope|Granadina|Sirope de flor de saúco, Horchata, Bebida isotónica|Aquarius isotónica|Powerade|Gatorade, Sidra, Agua de coco, Tequila|Mezcal|Pisco|Brandy|Coñac
    `,
    tk: `
      Pizza congelada|Pizza|Pizzas, Patatas congeladas|Patatas fritas congeladas|Patatas para horno|Gajos de patata|Croquetas de patata|Rösti, Croquetas|Croquetas de jamón|Croquetas congeladas,
      Varitas de pescado|Palitos de pescado|Pescado rebozado|Merluza rebozada|Calamares a la romana, Verduras congeladas|Espinacas congeladas|Salteado congelado|Menestra congelada|Judías verdes congeladas|Verduras para wok congeladas,
      Guisantes|Guisantes congelados|Arvejas|Chícharos|Petit pois, Frutos rojos congelados|Frambuesas congeladas|Arándanos congelados|Fruta congelada, Mango congelado|Mezcla para smoothie,
      Helado|Helados|Tarrina de helado|Polos|Sorbete|Magnum|Ben & Jerry’s|Ben and Jerrys|Häagen-Dazs|Cornetto|Bombón helado, Edamame, Nuggets|Nuggets de pollo|San Jacobos|Delicias de pollo, Hierbas congeladas,
      Pan congelado|Bollería congelada|Cruasanes congelados, Rollitos de primavera|Nems|Samosas, Lasaña congelada|Platos congelados|Comida congelada|Paella congelada, Cubitos de hielo|Hielo|Bolsa de hielo|Hielo picado,
      Gambas congeladas|Langostinos congelados, Hojaldre congelado, Empanadillas congeladas|Gyozas|Dim sum|Dumplings, Pescado congelado, Pollo congelado, Mariscos congelados|Mezcla de marisco,
      Pan de ajo, Gofres congelados|Tortitas congeladas, Maíz congelado
    `,
    drogerie: `
      Desodorante|Deo|Antitranspirante|Desodorante roll-on|Desodorante en spray|Desodorante en barra, Pasta de dientes|Dentífrico|Pasta dental|Crema dental|Colgate|Sensodyne|Signal|Oral-B|Licor del Polo,
      Cepillo de dientes|Cepillos de dientes|Cabezales|Recambios cepillo eléctrico, Hilo dental|Seda dental|Cepillos interdentales|Palillos, Enjuague bucal|Colutorio|Listerine,
      Gel de ducha|Gel de baño|Gel, Champú|Champu|Shampoo|Champú anticaspa, Acondicionador|Suavizante para el pelo|Bálsamo capilar, Mascarilla para el pelo|Mascarilla capilar|Aceite para el pelo,
      Gomina|Gel fijador|Laca|Cera para el pelo|Espuma para el pelo, Jabón|Jabón líquido|Jabón de manos|Pastilla de jabón|Jabón de Marsella, Crema de manos, Loción corporal|Crema corporal|Leche corporal|Crema hidratante,
      Crema facial|Crema de día|Crema de noche|Nivea|Hidratante facial, Crema solar|Protector solar|Bronceador|Spray solar|Aftersun|After sun,
      Bálsamo labial|Protector labial|Cacao para labios|Labello, Cuchillas de afeitar|Maquinillas|Maquinilla|Cuchillas|Maquinillas desechables, Espuma de afeitar|Gel de afeitar, Aftershave|Loción para después del afeitado,
      Discos desmaquillantes|Algodones desmaquillantes|Discos de algodón, Bastoncillos|Bastoncillos de algodón|Hisopos|Cotonetes, Algodón, Pañuelos|Kleenex|Pañuelos de papel|Clínex|Pañuelos desechables,
      Papel higiénico|Papel de váter|Papel del váter|Rollos de papel higiénico|Papel de baño|Papel toilette, Toallitas|Toallitas húmedas|Toallitas de bebé|Papel higiénico húmedo, Tiritas|Curitas|Apósitos|Esparadrapo|Compeed,
      Tampones|Compresas|Protegeslips|Salvaslips|Higiene íntima femenina|Copa menstrual|Toallas sanitarias, Preservativos|Condones, Lima de uñas|Esmalte de uñas|Pintaúñas|Quitaesmalte|Cortaúñas,
      Maquillaje|Rímel|Máscara de pestañas|Pintalabios|Barra de labios|Polvos|Corrector|Base de maquillaje|Lápiz de ojos|Sombra de ojos, Desmaquillante|Agua micelar|Tónico|Limpiador facial|Gel limpiador,
      Perfume|Colonia|Eau de toilette, Líquido de lentillas|Lentillas|Lentes de contacto|Suero fisiológico, Vitaminas|Suplementos|Complementos alimenticios|Magnesio|Vitamina D|Zinc|Pastillas efervescentes,
      Pañales|Dodot|Pañales de bebé|Pampers, Potitos|Comida para bebé|Papillas|Leche de fórmula, Gomas de pelo|Coleteros|Horquillas|Cepillo de pelo|Peine, Crema de pies,
      Paracetamol|Ibuprofeno|Aspirina|Analgésicos, Caramelos para la garganta|Jarabe para la tos|Spray nasal, Tapones para los oídos, Vela aromática, Gel íntimo, Gel hidroalcohólico|Gel desinfectante
    `,
    haushalt: `
      Lavavajillas a mano|Lavavajillas|Fairy|Mistol|Jabón de platos|Detergente para platos|Lavaplatos, Pastillas lavavajillas|Pastillas para el lavavajillas|Cápsulas lavavajillas|Finish|Somat|Detergente lavavajillas,
      Abrillantador, Sal para lavavajillas|Sal lavavajillas, Detergente|Detergente para ropa|Detergente líquido|Detergente en polvo|Cápsulas de detergente|Ariel|Skip|Dixan|Colón|Wipp|Jabón para ropa,
      Suavizante|Mimosín|Flor|Lenor, Quitamanchas|Vanish|Spray quitamanchas|Jabón quitamanchas, Limpiador multiusos|Limpiador|Producto de limpieza|Don Limpio|Cif|KH-7|Spray limpiador|Fregasuelos multiusos,
      Limpiacristales|Limpiador de cristales, Limpiador de baño|Antical|Quitacal|Desincrustante, Descalcificador|Antical cafetera, Limpiador WC|Lejía|Pato WC|Bloque WC|Harpic|Cloro,
      Estropajos|Estropajo|Esponjas|Esponja|Scotch-Brite|Estropajo de acero, Bayetas|Bayeta|Paños|Paños de microfibra|Trapos|Balletas|Fregona, Papel de cocina|Rollos de cocina|Servilletas de cocina|Toallas de papel,
      Bolsas de basura|Bolsas de basura grandes|Bolsas orgánicas|Bolsas de compost, Papel de aluminio|Papel albal|Albal|Aluminio, Film transparente|Papel film|Film alimentario, Papel de horno|Papel vegetal|Papel sulfurizado,
      Bolsas de congelación|Bolsas zip|Bolsas herméticas|Bolsas para bocadillo, Pilas|Pilas AA|Pilas AAA|Baterías, Bombillas|Bombilla|Bombilla LED|Focos, Velas|Velas de té|Velitas, Cerillas|Mechero|Fósforos|Encendedor,
      Servilletas|Servilletas de papel, Platos de papel|Platos desechables|Vasos de plástico|Vasos de papel|Pajitas|Cubiertos desechables, Carbón vegetal|Pastillas de encendido|Carbón para barbacoa,
      Comida para gatos|Pienso para gatos|Comida para perros|Pienso para perros|Arena para gatos|Comida para mascotas|Premios para perros|Snacks para perros,
      Tierra para plantas|Sustrato|Abono|Fertilizante, Desatascador|Desatascador de tuberías|Viakal, Limpiahornos|Limpiador de horno, Fregasuelos|Limpiador de suelos|Limpiador de parquet, Vinagre de limpieza,
      Pinzas de la ropa|Pinzas, Bolsas de aspiradora, Guantes de fregar|Guantes|Guantes desechables, Ambientador|Ambientadores|Spray ambientador|Air Wick, Antipolillas, Betún|Crema para zapatos, Plumero
    `,
    sonstiges: ``,
  },

  // Beispiele für den Verlauf beim ersten Öffnen, damit Vorschläge und Schnellauswahl gleich etwas anbieten
  start: ['Leche', 'Pan', 'Huevos', 'Mantequilla', 'Plátanos', 'Manzanas', 'Tomates', 'Pepino', 'Cebollas', 'Patatas', 'Queso', 'Yogur',
    'Pechuga de pollo', 'Carne picada', 'Pasta', 'Arroz', 'Café', 'Té', 'Zumo de naranja', 'Papel higiénico', 'Lavavajillas',
    'Pasta de dientes', 'Salmón', 'Zanahorias', 'Calabacín', 'Aceite de oliva', 'Chocolate', 'Patatas fritas', 'Tomate triturado',
    'Mozzarella', 'Jamón serrano', 'Aguacates'],

  // Typischer Vorrat: im Rezept-Prüfblatt standardmäßig abgewählt
  vorrat: ['Sal', 'Pimienta', 'Pimienta negra', 'Aceite', 'Aceite de oliva', 'Harina', 'Azúcar', 'Agua', 'Vinagre', 'Canela', 'Pimentón',
    'Levadura química', 'Curry', 'Nuez moscada', 'Orégano', 'Maicena', 'Azúcar avainillado', 'Caldo de verduras', 'Pastillas de caldo',
    'Guindilla seca', 'Comino', 'Laurel', 'Bicarbonato', 'Salsa de soja', 'Tomillo', 'Perejil seco', 'Ajo en polvo'],
};
