// Sprachpaket Französisch: Texte der Oberfläche, Artikelkatalog, Startverlauf und typischer Vorrat.
// Schlüssel der Texte ist der deutsche Text aus index.html; {0}, {1} … sind eingesetzte Werte.
// Katalog im selben Format wie katalog.js: Einträge durch Komma getrennt, Synonyme durch „|“, „~“ = Falschschreibung.

(window.SPRACHPAKETE = window.SPRACHPAKETE || {}).fr = {
  texte: {
    'Einkaufsliste': 'Liste de courses',
    'Speichern fehlgeschlagen': 'Échec de l’enregistrement',
    'Supermarkt': 'Supermarché',
    'Drogerie': 'Droguerie',
    'Stück': 'pièces',
    '{0}: diesmal nicht': '{0} : pas cette fois',
    'Rückgängig': 'Annuler',
    '{0} gelöscht': 'Supprimé : {0}',
    'Auch die Stammartikel werden entfernt.': 'Les articles habituels seront aussi supprimés.',
    'Die ganze Einkaufsliste löschen ({0} Artikel)?': { one: 'Supprimer toute la liste de courses ({0} article) ?', other: 'Supprimer toute la liste de courses ({0} articles) ?' },
    'Liste gelöscht': 'Liste supprimée',
    'Einkauf abgeschlossen ({0})': 'Courses terminées ({0})',
    'Rezept · {0} Zutaten': { one: 'Recette · {0} ingrédient', other: 'Recette · {0} ingrédients' },
    'schon auf der Liste': 'déjà sur la liste',
    'Korrektur': 'correction',
    'zuordnen': 'classer',
    'Diesmal nicht': 'Pas cette fois',
    'Löschen': 'Supprimer',
    'Zurückholen': 'Remettre',
    'Abhaken': 'Cocher',
    'Laden': 'Magasin',
    'Laden wählen': 'Choisir le magasin',
    'Die Liste ist leer.': 'La liste est vide.',
    'Oben eintragen, scannen oder ein Rezept übernehmen.': 'Saisissez en haut, scannez ou ajoutez une recette.',
    'Nicht in diesem Laden ({0})': 'Pas dans ce magasin ({0})',
    'Diesmal nicht:': 'Pas cette fois :',
    'Ganze Liste löschen': 'Supprimer toute la liste',
    'Einkauf abschließen · {0} erledigt': 'Terminer les courses · {0} fait(s)',
    'Schnellauswahl': 'Choix rapide',
    'Schnellauswahl zeigen': 'Afficher le choix rapide',
    'Schnellauswahl ausblenden': 'Masquer le choix rapide',
    'Kein Rezept {0}': 'Pas de recette {0}',
    'Noch keine Rezepte gespeichert': 'Aucune recette enregistrée',
    'Abbrechen': 'Annuler',
    'Nicht mehr anheften': 'Ne plus épingler',
    'Immer in der Schnellauswahl zeigen': 'Toujours afficher dans le choix rapide',
    'Nicht mehr vorschlagen': 'Ne plus proposer',
    'Verwalten unter Einstellungen → Schnellauswahl.': 'Gérer dans Réglages → Choix rapide.',
    'Artikel': 'Article',
    'Fertig': 'OK',
    'Name': 'Nom',
    'Menge': 'Quantité',
    'Weniger': 'Moins',
    'Mehr': 'Plus',
    'Abteilung': 'Rayon',
    'Marke / Notiz': 'Marque / note',
    'z. B. Alnatura, 1,5 %': 'p. ex. bio, demi-écrémé',
    'Wird immer benötigt': 'Toujours nécessaire',
    'Steht nach jedem Einkauf von selbst wieder auf der Liste': 'Revient tout seul sur la liste après chaque course',
    'Von der Liste löschen': 'Supprimer de la liste',
    'Abteilung wählen. Die App merkt sich das für diesen Artikel.': 'Choisissez un rayon. L’app s’en souviendra pour cet article.',
    'Angeheftet, immer zuerst': 'Épinglés, toujours en premier',
    'Lösen': 'Détacher',
    'Danach automatisch die häufigsten Käufe, ohne Stammartikel. Auch in der Schnellauswahl: Chip lange drücken.':
      'Ensuite, vos achats les plus fréquents, sans les articles habituels. Dans le choix rapide, vous pouvez aussi appuyer longuement sur une puce.',
    'Anheften': 'Épingler',
    'Ausblenden': 'Masquer',
    'Noch nichts gekauft.': 'Rien acheté pour l’instant.',
    'Ausgeblendet': 'Masqués',
    'Wieder zeigen': 'Réafficher',
    'Automatisch ({0})': 'Automatique ({0})',
    'Einstellungen': 'Réglages',
    'Läden': 'Magasins',
    'Standort gespeichert': 'position enregistrée',
    '{0} Abteilungen': { one: '{0} rayon', other: '{0} rayons' },
    'Laden hinzufügen': 'Ajouter un magasin',
    'Laden per Standort wählen': 'Choisir le magasin selon la position',
    'Beim Öffnen im Laden passendes Profil einstellen': 'À l’ouverture dans un magasin, passer à ce magasin',
    'Sprache': 'Langue',
    'Gilt für Texte, Abteilungen und die Erkennung der Artikel. Schon eingetragene Artikel behalten ihren Namen.':
      'S’applique aux textes, aux rayons et à la reconnaissance des articles. Les articles déjà sur la liste gardent leur nom.',
    'Darstellung': 'Affichage',
    'Automatisch': 'Automatique',
    'Hell': 'Clair',
    'Dunkel': 'Sombre',
    'Abteilungen farbig markieren': 'Colorer les rayons',
    'Farbe je Bereich im Laden, die Beschriftung bleibt': 'Une couleur par zone du magasin, les noms restent',
    'Abteilung in der Listenansicht zeigen': 'Afficher le rayon dans la liste',
    'Name der Abteilung rechts neben dem Artikel': 'Nom du rayon à droite de l’article',
    'Streifen': 'Bandes',
    'Farbige Zeilen': 'Lignes colorées',
    'Nur in der Listenansicht, wenn das Eingabefeld leer ist': 'Seulement dans la liste, quand le champ de saisie est vide',
    'Anzeigen': 'Afficher',
    'Beim Antippen': 'Au toucher',
    'Immer': 'Toujours',
    'Immer unter dem Eingabefeld. Nach oben wischen blendet sie aus, antippen oder nach unten wischen holt sie zurück.':
      'Toujours sous le champ de saisie. Glissez vers le haut pour le masquer, touchez ou glissez vers le bas pour le faire revenir.',
    'Erscheint, sobald du ins Eingabefeld tippst, und bei leerer Liste.': 'Apparaît dès que vous touchez le champ de saisie, et quand la liste est vide.',
    'Anzahl': 'Nombre',
    'Artikel anheften': 'Épingler un article',
    'Version {0}': 'Version {0}',
    'Aus einem Rezept': 'D’une recette',
    'Stammartikel': 'Articles habituels',
    'Entfernen': 'Retirer',
    'Noch keine. Artikel antippen und „Wird immer benötigt“ einschalten.': 'Aucun. Touchez un article et activez « Toujours nécessaire ».',
    'Rezepte': 'Recettes',
    '{0} Zutaten': { one: '{0} ingrédient', other: '{0} ingrédients' },
    'Noch keine. Beim Übernehmen eines Rezepts einen Namen vergeben, dann im Eingabefeld mit #Name abrufen.':
      'Aucune. Donnez un nom à une recette en l’ajoutant, puis rappelez-la dans le champ de saisie avec #Nom.',
    'Daten': 'Données',
    "Einzelne Funktionen fragen Dienste im Internet, aber nur, wenn du sie benutzt: Barcode-Scan (Open Food Facts: die Nummer), Karte für Läden (OpenStreetMap: Kartenausschnitt und Suchtext). Der Standort wird nur auf dem Gerät ausgewertet. Auch Rezeptfotos erkennt die App auf dem Gerät: Beim ersten Mal lädt sie dafür die Texterkennung herunter, das Foto selbst wird nicht übertragen.": "Certaines fonctions interrogent des services sur Internet, mais uniquement quand tu les utilises : scan de code-barres (Open Food Facts : le numéro), carte des magasins (OpenStreetMap : zone de la carte et texte de recherche). La position n’est analysée que sur l’appareil. Les photos de recettes sont elles aussi lues sur l’appareil : la première fois, l’app télécharge pour cela la reconnaissance de texte ; la photo elle-même n’est jamais transmise.",
    "Auf dem Gerät gilt der Schutz deines iPhones, zum Beispiel der Sperrcode. Die App verschlüsselt lokal nichts zusätzlich. Die Sicherungsdatei (Einstellungen → Daten) ist unverschlüsselt, bewahre sie entsprechend auf.": "Sur l’appareil, c’est la protection de ton iPhone qui s’applique, par exemple le code de verrouillage. L’app n’ajoute aucun chiffrement local. Le fichier de sauvegarde (Réglages → Données) n’est pas chiffré, conserve-le en conséquence.",
    "Foto auswählen": "Choisir une photo",
    "So kommen die Zutaten ins Feld": "Comment mettre les ingrédients dans le champ",
    "Mit der Kamera: Ins Feld „Zutaten“ tippen, noch einmal tippen und „Text scannen“ wählen. Dann die Kamera auf die Zutatenliste halten und „Einsetzen“ tippen.": "Avec l’appareil photo : touche le champ « Ingrédients », touche-le encore une fois et choisis « Scanner du texte ». Vise ensuite la liste des ingrédients et touche « Insérer ».",
    "Aus einem Foto oder Screenshot: Den Text im Bild gedrückt halten, die Zutaten markieren, kopieren und hier einfügen.": "Depuis une photo ou une capture d’écran : maintiens le doigt sur le texte de l’image, sélectionne les ingrédients, copie-les et colle-les ici.",
    "Oder „Foto auswählen“: Die App liest den Text selbst, auf dem Gerät. Das Ergebnis erscheint im Feld und kann vor dem Übernehmen korrigiert werden.": "Ou « Choisir une photo » : l’app lit le texte elle-même, sur l’appareil. Le résultat apparaît dans le champ et peut être corrigé avant l’ajout.",
    "Texterkennung wird geladen": "Chargement de la reconnaissance de texte",
    "Text wird erkannt: {0} %": "Reconnaissance du texte : {0} %",
    "Auf dem Foto wurde kein Text erkannt. Am besten die Zutatenliste gerade und formatfüllend fotografieren.": "Aucun texte n’a été reconnu sur la photo. Le mieux est de photographier la liste des ingrédients bien droite et en plein cadre.",
    "Text erkannt. Bitte prüfen, Überflüssiges löschen und dann „Zutaten übernehmen“ tippen.": "Texte reconnu. Vérifie-le, supprime ce qui est inutile, puis touche « Ajouter les ingrédients ».",
    "Datenschutz": "Confidentialité",
    "Wo deine Daten liegen": "Où sont stockées tes données",
    "Liste, Verlauf, Rezepte, Läden, Kundenkarten und Einstellungen liegen nur auf diesem Gerät, im Speicher der App. Es gibt kein Konto und keine Anmeldung.": "La liste, l’historique, les recettes, les magasins, les cartes de fidélité et les réglages sont stockés uniquement sur cet appareil, dans la mémoire de l’app. Il n’y a ni compte ni connexion.",
    "Wie sie übertragen werden": "Comment elles sont transmises",
    "Ohne Synchronisierung verlässt keine Liste dein Gerät. Mit Synchronisierung werden die Daten auf dem Gerät verschlüsselt (AES-256), bevor sie an den Server gehen. Der Schlüssel steckt nur in der Einladung (QR-Code oder Link) und geht nie an den Server. Der Server kann die Daten nicht lesen.": "Sans synchronisation, aucune liste ne quitte ton appareil. Avec la synchronisation, les données sont chiffrées sur l’appareil (AES-256) avant d’être envoyées au serveur. La clé se trouve uniquement dans l’invitation (code QR ou lien) et n’est jamais envoyée au serveur. Le serveur ne peut pas lire les données.",
    "Eine geteilte Liste steckt unverschlüsselt im Link. Wer den Link hat, kann sie lesen.": "Une liste partagée est contenue sans chiffrement dans le lien. Toute personne qui a le lien peut la lire.",
    "Wie sie gesichert sind": "Comment elles sont protégées",
    "Auf dem Server liegt nur der verschlüsselte Block. Ein Haushalt, den drei Monate lang niemand benutzt hat, wird dort automatisch gelöscht. Mit „Neuen Schlüssel erzeugen“ verlieren alle anderen Geräte den Zugriff.": "Le serveur ne contient que le bloc chiffré. Un foyer que personne n’a utilisé pendant trois mois y est supprimé automatiquement. Avec « Créer une nouvelle clé », tous les autres appareils perdent l’accès.",
    "Anonyme Nutzungsstatistik": "Statistiques d’utilisation anonymes",
    "Damit sichtbar wird, wie viele Geräte die App nutzen, sendet sie höchstens einmal am Tag eine zufällige Kennung und ob die Synchronisierung an ist. Die Kennung ist keine Gerätekennung des iPhones und mit keinem Namen, keiner Liste und keinem Ort verknüpft. Übertragen werden keine Artikel, Listen, Standorte oder Namen. Gezählt werden nur aktive Geräte je Tag.": "Pour savoir combien d’appareils utilisent l’app, elle envoie au plus une fois par jour un identifiant aléatoire et l’état de la synchronisation. L’identifiant n’est pas un identifiant de l’iPhone et n’est lié à aucun nom, aucune liste ni aucun lieu. Aucun article, liste, position ou nom n’est transmis. Seuls les appareils actifs par jour sont comptés.",
    "Das gilt für alle verbundenen Geräte.": "Cela s’applique à tous les appareils connectés.",
    "{0} auf einem anderen Gerät gelöscht": "{0} supprimé sur un autre appareil",
    "{0} Artikel auf einem anderen Gerät gelöscht": "{0} articles supprimés sur un autre appareil",
    "Synchronisieren": "Synchroniser",
    "An": "Activé",
    "Mehrere iPhones teilen sich dieselbe Liste, dieselben Läden und Rezepte. Ein Konto braucht es nicht: Wer die Einladung hat, gehört dazu. Die Daten werden auf dem Gerät verschlüsselt, der Server sieht nur unlesbare Daten.": "Plusieurs iPhone partagent la même liste, les mêmes magasins et recettes. Aucun compte nécessaire : qui a l’invitation en fait partie. Les données sont chiffrées sur l’appareil, le serveur ne voit que des données illisibles.",
    "Synchronisierung einrichten": "Configurer la synchronisation",
    "Der Sync-Server ist noch nicht eingerichtet.": "Le serveur de synchronisation n’est pas encore configuré.",
    "Schon eingeladen? Den Link ins Eingabefeld der Liste einfügen oder den QR-Code mit dem Scanner der App scannen.": "Déjà invité ? Collez le lien dans le champ de saisie de la liste ou scannez le code QR avec le scanner de l’app.",
    "Weiteres Gerät einladen": "Inviter un autre appareil",
    "Auf dem anderen iPhone in der App den Scanner öffnen und diesen Code scannen. Oder den Link schicken.": "Sur l’autre iPhone, ouvrez le scanner de l’app et scannez ce code. Ou envoyez le lien.",
    "Einladung teilen": "Partager l’invitation",
    "Jetzt synchronisieren": "Synchroniser maintenant",
    "Verbindung": "Connexion",
    "Auf diesem Gerät beenden": "Arrêter sur cet appareil",
    "Neuen Schlüssel erzeugen": "Créer une nouvelle clé",
    "Ein neuer Schlüssel trennt alle anderen Geräte. Sie müssen neu eingeladen werden.": "Une nouvelle clé déconnecte tous les autres appareils. Ils devront être invités à nouveau.",
    "Wird eingerichtet": "Configuration",
    "Verbindung fehlgeschlagen. Später erneut versuchen.": "Échec de la connexion. Réessayez plus tard.",
    "Einladung zu unserer gemeinsamen Einkaufsliste:": "Invitation à notre liste de courses commune :",
    "Wird synchronisiert": "Synchronisation",
    "Synchronisierung auf diesem Gerät beenden? Die Daten bleiben hier, werden aber nicht mehr abgeglichen.": "Arrêter la synchronisation sur cet appareil ? Les données restent ici mais ne seront plus synchronisées.",
    "Neuen Schlüssel erzeugen? Alle anderen Geräte werden getrennt und müssen neu eingeladen werden.": "Créer une nouvelle clé ? Tous les autres appareils seront déconnectés et devront être invités à nouveau.",
    "Sicherung einspielen? Die aktuellen Daten werden ersetzt, auch auf allen verbundenen Geräten.": "Restaurer la sauvegarde ? Les données actuelles seront remplacées, aussi sur tous les appareils connectés.",
    "Die gemeinsame Liste wurde beendet oder neu eingerichtet": "La liste commune a été arrêtée ou reconfigurée",
    "Schlüssel passt nicht zu den Daten": "La clé ne correspond pas aux données",
    "Synchronisierung fehlgeschlagen": "Échec de la synchronisation",
    "QR-Code": "Code QR",
    "Offline. Änderungen werden später übertragen.": "Hors ligne. Les modifications seront envoyées plus tard.",
    "Noch nicht synchronisiert": "Pas encore synchronisé",
    "Verbunden · gerade eben": "Connecté · à l’instant",
    "Verbunden · zuletzt vor {0} Min.": "Connecté · il y a {0} min",
    "Schon verbunden": "Déjà connecté",
    "Gemeinsame Liste": "Liste commune",
    "Mit der gemeinsamen Liste verbinden? Danach sehen alle verbundenen Geräte dieselbe Liste, dieselben Läden und Rezepte.": "Se connecter à la liste commune ? Tous les appareils connectés verront alors la même liste, les mêmes magasins et recettes.",
    "Die bisherige Verbindung dieses Geräts wird dabei beendet.": "La connexion actuelle de cet appareil sera arrêtée.",
    "Verbinden und zusammenführen": "Connecter et fusionner",
    "Verbinden, Daten dieses Geräts ersetzen": "Connecter et remplacer les données de cet appareil",
    "Zusammenführen behält, was nur auf diesem Gerät steht. Ersetzen übernimmt nur die gemeinsame Liste.": "Fusionner garde ce qui n’existe que sur cet appareil. Remplacer ne reprend que la liste commune.",
    "Wird verbunden": "Connexion en cours",
    "Verbunden": "Connecté",
    'Einkaufen': 'Courses',
    'Keine': 'Aucun',
    'Anzeige': 'Interface',
    'Aus': 'Désactivé',
    'Erweitert': 'Avancé',
    'Erscheinungsbild': 'Apparence',
    'Abteilungen': 'Rayons',
    'Sicherung exportieren': 'Exporter une sauvegarde',
    'Sicherung importieren': 'Importer une sauvegarde',
    'Verlauf und gelernte Zuordnungen löschen': 'Effacer l’historique et les rayons appris',
    '{0} Artikel im Verlauf · {1} gelernte Zuordnungen · {2} Katalogbegriffe': '{0} articles dans l’historique · {1} rayons appris · {2} termes du catalogue',
    'Neuer Laden': 'Nouveau magasin',
    'Verlauf, gelernte Abteilungen und gespeicherte Barcodes löschen? Die aktuelle Liste bleibt.':
      'Effacer l’historique, les rayons appris et les codes-barres enregistrés ? La liste actuelle est conservée.',
    'Zurück': 'Retour',
    'z. B. REWE Hauptstraße': 'p. ex. Carrefour Centre-ville',
    'Laufweg': 'Parcours dans le magasin',
    'Am Griff ziehen, um die Reihenfolge zu ändern. Haken entfernen, wenn es die Abteilung in diesem Laden nicht gibt.':
      'Faites glisser la poignée pour changer l’ordre. Décochez un rayon si ce magasin ne l’a pas.',
    'Namen antippen, um die Abteilung umzubenennen.': 'Touchez un nom pour renommer le rayon.',
    'Abteilung hinzufügen': 'Ajouter un rayon',
    'Neue Abteilung': 'Nouveau rayon',
    'z. B. Asia & Internationales': 'p. ex. Asie & international',
    'Die neue Abteilung gibt es in allen Läden, jeweils vor „Sonstiges“. Im Laufweg lässt sie sich verschieben oder ausblenden.': 'Le nouveau rayon est ajouté à tous les magasins, juste avant « Divers ». Dans le parcours, vous pouvez le déplacer ou le masquer.',
    'Eigene Abteilung. Name und Löschen gelten für alle Läden.': 'Rayon personnel. Le nom et la suppression valent pour tous les magasins.',
    'Der Name gilt nur für „{0}“. Ursprünglich: {1}.': 'Ce nom ne vaut que pour « {0} ». Nom d’origine : {1}.',
    'Ursprünglichen Namen verwenden': 'Reprendre le nom d’origine',
    'Abteilung löschen': 'Supprimer le rayon',
    'Abteilung „{0}“ löschen? Die Artikel darin werden neu einsortiert.': 'Supprimer le rayon « {0} » ? Ses articles seront triés à nouveau.',
    'In diesem Laden vorhanden': 'Présent dans ce magasin',
    'Verschieben': 'Déplacer',
    'Standort': 'Position',
    'Nicht gespeichert. Auf der Karte wählen oder im Laden stehend übernehmen, dann wählt die App diesen Laden automatisch.':
      'Non enregistrée. Choisissez-la sur la carte ou enregistrez-la depuis le magasin ; l’app choisira alors ce magasin automatiquement.',
    'Auf der Karte gewählt: {0}.': 'Choisie sur la carte : {0}.',
    'Auf der Karte gewählt.': 'Choisie sur la carte.',
    'Gespeichert (±{0} m).': 'Enregistrée (±{0} m).',
    'Auf der Karte wählen': 'Choisir sur la carte',
    'Aktuellen Standort übernehmen': 'Utiliser la position actuelle',
    'Standort entfernen': 'Supprimer la position',
    'Laden löschen': 'Supprimer le magasin',
    'Standort wird bestimmt': 'Localisation en cours',
    'Standort nicht verfügbar': 'Position non disponible',
    '„{0}“ löschen?': 'Supprimer « {0} » ?',
    'Sicherung einspielen? Die aktuellen Daten werden ersetzt (der API-Schlüssel bleibt).':
      'Restaurer la sauvegarde ? Les données actuelles seront remplacées (la clé API est conservée).',
    'Sicherung eingespielt': 'Sauvegarde restaurée',
    'Datei konnte nicht gelesen werden': 'Impossible de lire le fichier',
    'Standort wählen': 'Choisir la position',
    'Adresse oder Markt suchen': 'Rechercher une adresse ou un magasin',
    'Karte wird geladen': 'Chargement de la carte',
    'Standort übernehmen': 'Utiliser cette position',
    'Die Karte konnte nicht geladen werden. Bitte Internetverbindung prüfen.': 'Impossible de charger la carte. Vérifiez votre connexion internet.',
    'Namen übernehmen': 'Reprendre le nom',
    'Nadel gesetzt. Tippe auf einen Markt-Punkt, um auch den Namen zu übernehmen.': 'Épingle placée. Touchez le point d’un magasin pour reprendre aussi son nom.',
    'Zum Anzeigen der Märkte näher heranzoomen oder oben suchen.': 'Zoomez pour voir les magasins, ou recherchez en haut.',
    'Märkte werden gesucht …': 'Recherche des magasins …',
    '1 Markt: Punkt antippen oder Nadel per Tippen auf die Karte setzen.': '1 magasin : touchez le point, ou touchez la carte pour placer une épingle.',
    '{0} Märkte: Punkt antippen oder Nadel per Tippen auf die Karte setzen.': '{0} magasins : touchez un point, ou touchez la carte pour placer une épingle.',
    'Hier keine Märkte gefunden. Nadel per Tippen auf die Karte setzen.': 'Aucun magasin trouvé ici. Touchez la carte pour placer une épingle.',
    'Märkte gerade nicht abrufbar. Nadel per Tippen auf die Karte setzen.': 'Magasins indisponibles pour le moment. Touchez la carte pour placer une épingle.',
    'Standort wird bestimmt …': 'Localisation en cours …',
    'Adresse oder Markt oben suchen, oder die Karte verschieben und heranzoomen.': 'Recherchez une adresse ou un magasin en haut, ou déplacez la carte et zoomez.',
    'Suche …': 'Recherche …',
    'Suche gerade nicht erreichbar': 'Recherche indisponible pour le moment',
    'Nichts gefunden': 'Aucun résultat',
    'Standort gespeichert: {0}': 'Position enregistrée : {0}',
    'Erst bei einem Laden den Standort speichern': 'Enregistrez d’abord la position d’un magasin',
    'Laden: {0}': 'Magasin : {0}',
    'Kein gespeicherter Laden in der Nähe': 'Aucun magasin enregistré à proximité',
    'Nummer eingeben': 'Saisir le numéro',
    'Barcode in den Rahmen halten': 'Placez le code-barres dans le cadre',
    'EAN-Nummer (unter dem Barcode):': 'Numéro EAN (sous le code-barres) :',
    'Kamera nicht verfügbar. Zugriff in den Einstellungen erlauben oder Nummer eingeben.':
      'Caméra indisponible. Autorisez l’accès dans les réglages ou saisissez le numéro.',
    'Die Kamera geht nur, wenn die App über https geöffnet wird. Nummer eingeben geht trotzdem.':
      'La caméra ne fonctionne que si l’app est ouverte en https. La saisie du numéro fonctionne quand même.',
    '„{0}“ ist keine EAN-Nummer (8 bis 14 Ziffern).': '« {0} » n’est pas un numéro EAN (8 à 14 chiffres).',
    'Kamera unterbrochen. Hier tippen, um neu zu starten.': 'Caméra interrompue. Touchez ici pour redémarrer.',
    'Code nicht lesbar. Etwas Abstand halten, für Licht sorgen oder die Nummer eingeben.': 'Code illisible. Éloignez un peu, ajoutez de la lumière ou saisissez le numéro.',
    'Barcode {0}': 'Code-barres {0}',
    'Produkt wird gesucht': 'Recherche du produit',
    'Schon einmal gescannt.': 'Déjà scanné.',
    'Gefunden. Name bei Bedarf kürzen.': 'Trouvé. Raccourcissez le nom si besoin.',
    'Nicht in der Produktdatenbank. Einmal benennen, dann merkt sich die App den Barcode.':
      'Absent de la base de produits. Nommez-le une fois et l’app retiendra le code-barres.',
    'z. B. Alpro Haferdrink Barista 1 l': 'p. ex. Bjorg boisson avoine 1 l',
    'Hinzufügen': 'Ajouter',
    'auf der Liste': 'sur la liste',
    'Vorrat': 'placard',
    'Rezept übernehmen': 'Ajouter une recette',
    'Gespeicherte Rezepte': 'Recettes enregistrées',
    'Zutaten': 'Ingrédients',
    '200 g Spaghetti&#10;2 Zehen Knoblauch&#10;1 Bund Basilikum': '200 g de spaghetti&#10;2 gousses d’ail&#10;1 bouquet de basilic',
    'Zutaten übernehmen': 'Ajouter les ingrédients',
    'Keine Zutaten erkannt': 'Aucun ingrédient reconnu',
    'Fehler bei der Erkennung.': 'Erreur lors de la reconnaissance.',
    'Was brauchst du?': 'De quoi avez-vous besoin ?',
    'Abwählen, was noch im Vorrat ist. Name, Menge und Abteilung lassen sich antippen und ändern.':
      'Décochez ce que vous avez déjà. Touchez le nom, la quantité ou le rayon pour les modifier.',
    'Übernehmen': 'Inclure',
    'Name und Menge': 'Nom et quantité',
    'Als Rezept speichern (optional, alle Zutaten)': 'Enregistrer comme recette (facultatif, tous les ingrédients)',
    'Name, z. B. Chili sin Carne': 'Nom, p. ex. Chili végétarien',
    '1 Artikel hinzufügen': 'Ajouter 1 article',
    '{0} Artikel hinzufügen': 'Ajouter {0} articles',
    '{0} und Rezept speichern': '{0} et enregistrer la recette',
    'Nur Rezept speichern': 'Enregistrer seulement la recette',
    "Nur als Rezept speichern": "Enregistrer seulement comme recette",
    "Bitte einen Namen für das Rezept eingeben": "Saisis un nom pour la recette",
    'Rezept gespeichert, abrufen mit #{0}': 'Recette enregistrée, rappelez-la avec #{0}',
    'Es gibt schon ein Rezept „#{0}“. Ersetzen?': 'La recette « #{0} » existe déjà. La remplacer ?',
    'Name (abrufen mit #Name)': 'Nom (rappel avec #Nom)',
    'Zutat, z. B. 500 g Hackfleisch': 'Ingrédient, p. ex. 500 g de viande hachée',
    'Auf die Liste': 'Mettre sur la liste',
    'Rezept löschen': 'Supprimer la recette',
    '„#{0}“ gibt es schon': '« #{0} » existe déjà',
    'Name fehlt': 'Nom manquant',
    'Rezept „#{0}“ löschen?': 'Supprimer la recette « #{0} » ?',
    'Keine offenen Artikel zum Teilen': 'Aucun article à partager',
    'Einkaufsliste ({0} Artikel)': { one: 'Liste de courses ({0} article)', other: 'Liste de courses ({0} articles)' },
    'Zum Abhaken öffnen:': 'Ouvrir pour cocher :',
    'Liste teilen': 'Partager la liste',
    'Teilen': 'Partager',
    'Kopieren': 'Copier',
    'Kopiert, jetzt in eine Nachricht einfügen': 'Copié, collez-le maintenant dans un message',
    'Der Link ist unvollständig oder beschädigt': 'Le lien est incomplet ou endommagé',
    'Der Link stammt aus einer neueren Version der App': 'Le lien provient d’une version plus récente de l’app',
    'Es ist schon eine geteilte Liste mit abgehakten Artikeln offen. Durch die neue ersetzen?':
      'Une liste partagée avec des articles cochés est déjà ouverte. La remplacer par la nouvelle ?',
    'geteilt am {0}': 'partagée le {0}',
    '{0} Artikel': { one: '{0} article', other: '{0} articles' },
    'Die geteilte Liste ist leer.': 'La liste partagée est vide.',
    'Erledigt zurückschicken · {0} von {1}': 'Renvoyer · {0} sur {1} faits',
    'Geteilte Liste schließen? Die Häkchen gehen verloren. Schicke vorher die Rückmeldung, falls noch nicht geschehen.':
      'Fermer la liste partagée ? Les coches seront perdues. Envoyez d’abord votre retour si ce n’est pas fait.',
    'Einkauf erledigt: {0} von {1} Artikeln': 'Courses faites : {0} articles sur {1}',
    'Nicht bekommen:': 'Pas trouvé :',
    'In die Liste übernehmen:': 'Reporter dans la liste :',
    'Rückmeldung schicken': 'Envoyer le retour',
    'Rückmeldung': 'Retour',
    '{0} gekauft, {1} nicht bekommen.': '{0} acheté(s), {1} pas trouvé(s).',
    'Gekauft': 'Acheté',
    'Nicht bekommen (bleibt offen)': 'Pas trouvé (reste ouvert)',
    '1 Artikel steht nicht mehr auf dieser Liste.': '1 article n’est plus sur cette liste.',
    '{0} Artikel stehen nicht mehr auf dieser Liste.': '{0} articles ne sont plus sur cette liste.',
    'Nutzt du die App vom Home-Bildschirm? Dann kopiere den Link aus der Nachricht und füge ihn dort ins Eingabefeld ein. Safari und die App haben getrennte Listen.':
      'Vous utilisez l’app depuis l’écran d’accueil ? Copiez alors le lien du message et collez-le dans le champ de saisie de l’app. Safari et l’app ont des listes séparées.',
    '{0} als gekauft abhaken': 'Cocher {0} comme acheté(s)',
    'Nichts abzuhaken': 'Rien à cocher',
    '{0} abgehakt': '{0} coché(s)',
    // Abteilungen
    'Gemüse': 'Légumes',
    'Obst': 'Fruits',
    'Brot & Backwaren': 'Pain & Viennoiseries',
    'Molkerei & Eier': 'Crèmerie & Œufs',
    'Käse': 'Fromages',
    'Fleisch & Wurst': 'Boucherie & Charcuterie',
    'Fisch': 'Poissonnerie',
    'Tofu, Frischteig & Feinkost': 'Tofu, Pâtes fraîches & Traiteur',
    'Frühstück, Kaffee & Tee': 'Petit-déjeuner, Café & Thé',
    'Nudeln, Reis & Beilagen': 'Pâtes, Riz & Féculents',
    'Konserven & Saucen': 'Conserves & Sauces',
    'Öl, Essig & Gewürze': 'Huile, Vinaigre & Épices',
    'Backzutaten & Nüsse': 'Pâtisserie & Fruits secs',
    'Süßes & Snacks': 'Sucreries & Apéritif',
    'H-Milch & Pflanzendrinks': 'Lait UHT & Boissons végétales',
    'Getränke': 'Boissons',
    'Tiefkühl': 'Surgelés',
    'Drogerie & Körperpflege': 'Hygiène & Beauté',
    'Haushalt & Putzen': 'Entretien & Maison',
    'Sonstiges': 'Divers',
    // Bereiche und Farbschemata
    'Obst & Gemüse': 'Fruits & Légumes',
    'Brot': 'Pain',
    'Kühlregal': 'Frais',
    'Fleisch & Fisch': 'Viande & Poisson',
    'Trockenwaren': 'Épicerie',
    'Drogerie & Haushalt': 'Hygiène & Maison',
    'Markt': 'Marché',
    'Farben passend zur Ware: Gemüse grün, Brot gelb, Kühlregal blau, Fleisch rot.': 'Couleurs selon les produits : légumes en vert, pain en jaune, frais en bleu, viande en rouge.',
    'Kontrast': 'Contraste',
    'Größtmöglicher Abstand zwischen benachbarten Bereichen, auch bei Rot-Grün-Schwäche.': 'Écart maximal entre zones voisines, même en cas de daltonisme rouge-vert.',
    'Ruhig': 'Sobre',
    'Nur vier Farben für die großen Zonen: Frisch, Kühlung, Trocken, Drogerie.': 'Seulement quatre couleurs pour les grandes zones : frais, réfrigéré, épicerie, hygiène.',
    'Frisch': 'Frais',
    'Kühlung': 'Réfrigéré',
    'Trocken & Getränke': 'Épicerie & Boissons',
    // Kundenkarten, verbundene Geräte
    'Karte': 'Carte',
    'Kundenkarten': 'Cartes de fidélité',
    'Karte hinzufügen': 'Ajouter une carte',
    'Kundenkarten werden mit den verbundenen Geräten geteilt.': 'Les cartes de fidélité sont partagées avec les appareils connectés.',
    'Wird beendet': 'Déconnexion',
    'Das Display bleibt an. Heller geht es über das Kontrollzentrum.': 'L’écran reste allumé. Pour plus de luminosité, passez par le Centre de contrôle.',
    'Speichern': 'Enregistrer',
    'Neue Kundenkarte': 'Nouvelle carte de fidélité',
    'Kette': 'Enseigne',
    'z. B. REWE': 'p. ex. Carrefour',
    'Bezeichnung (freiwillig)': 'Libellé (facultatif)',
    'z. B. Anna oder Familienkarte': 'p. ex. Anna ou carte famille',
    'Anderen Screenshot wählen': 'Choisir une autre capture',
    'Screenshot wählen': 'Choisir une capture d’écran',
    'Mit der Kamera scannen': 'Scanner avec l’appareil photo',
    'Karte löschen': 'Supprimer la carte',
    'Kundenkarte {0} löschen?': 'Supprimer la carte de fidélité {0} ?',
    'App': 'App',
    'Browser': 'Navigateur',
    'Dieses Gerät': 'Cet appareil',
    'Gerade aktiv': 'Actif maintenant',
    'Zuletzt aktiv {0}': 'Actif {0}',
    'Code aus der Bonus-App der Kette als Screenshot hinterlegen oder die Plastikkarte scannen. Im Laden zeigt der Knopf unten links die Karte. Welche Kette gemeint ist, erkennt die App am Namen des gewählten Ladens, z. B. „REWE Hauptstraße“.': 'Enregistrez le code de l’application de fidélité par une capture d’écran, ou scannez la carte en plastique. En magasin, le bouton en bas à gauche affiche la carte. L’application reconnaît l’enseigne au nom du magasin choisi, p. ex. « Carrefour Bastille ».',
    'Code der Karte in den Rahmen halten': 'Placez le code de la carte dans le cadre',
    'Der Code konnte nicht geladen werden': 'Impossible de charger le code',
    'Dieser Code lässt sich nicht darstellen.': 'Ce code ne peut pas être affiché.',
    'Code': 'Code',
    'Screenshot vom Code aus der App der Kette wählen oder die Karte scannen. Erkannt werden QR-Code, Aztec-Code (REWE), Data Matrix und Strichcodes.': 'Choisissez une capture d’écran du code dans l’application de l’enseigne, ou scannez la carte. Sont reconnus : QR code, code Aztec, Data Matrix et codes-barres.',
    'Kein Code gefunden. Den Screenshot so wählen, dass der Code ganz und scharf zu sehen ist.': 'Aucun code trouvé. Choisissez une capture où le code est entièrement et nettement visible.',
    'Erkannt: {0}. Dieses Format kann die App noch nicht anzeigen.': 'Reconnu : {0}. L’application ne sait pas encore afficher ce format.',
    '{0} erkannt.': '{0} reconnu.',
    'Code wird gesucht': 'Recherche du code',
    'Das Bild konnte nicht gelesen werden ({0}).': 'Impossible de lire l’image ({0}).',
    'Angeheftet': 'Épinglé',
    '{0} in der Schnellauswahl angeheftet': '{0} épinglé dans la sélection rapide',
    '{0} nicht mehr angeheftet': '{0} n’est plus épinglé',
    'Oder einen Artikel auf der Liste nach rechts wischen.': 'Ou balayez un article de la liste vers la droite.',
    'Mit {0} Geräten': { one: 'Avec {0} appareil', other: 'Avec {0} appareils' },
    'Verbunden mit {0} Geräten': { one: 'Connecté à {0} appareil', other: 'Connecté à {0} appareils' },
    'Andere Geräte': 'Autres appareils',
    'Unter diesem Namen erscheint es auf den anderen Geräten.': 'C’est le nom que voient les autres appareils. Les mots restent en allemand dans toutes les langues, pour que le nom soit partout le même.',
    'Noch kein anderes Gerät verbunden. Mit dem QR-Code unten einladen.': 'Aucun autre appareil connecté. Invitez-en un avec le QR code ci-dessous.',
    'Safari und die App vom Home-Bildschirm zählen als zwei Geräte.': 'Safari et l’app de l’écran d’accueil comptent comme deux appareils.',
    '{0} steht schon auf der Liste': '{0} est déjà sur la liste',
    'Angeheftete Artikel, die schon auf der Liste stehen': 'Articles épinglés déjà sur la liste',
    'Platz behalten': 'Garder leur place',
    'Sie bleiben an ihrer Stelle, mit Haken markiert. Häufig gekaufte Artikel füllen nur die Plätze nach allen angehefteten.': 'Ils restent à leur place, marqués d’une coche. Les articles achetés souvent ne remplissent que les places après tous les épinglés.',
    'Sie verschwinden aus der Schnellauswahl, bis sie gekauft sind. An ihre Stelle rücken häufig gekaufte Artikel.': 'Ils disparaissent de la sélection rapide jusqu’à leur achat. Des articles achetés souvent prennent leur place.',
    // Feste Texte im HTML
    'Liste': 'Liste',
    'Geteilte Liste': 'Liste partagée',
    'Schließen': 'Fermer',
    'Artikel hinzufügen': 'Ajouter un article',
    'Barcode scannen': 'Scanner un code-barres',
    'Einkauf abschließen': 'Terminer les courses',
    'Kundenkarte zeigen': 'Afficher la carte de fidélité',
  },

  katalog: {
    gemuese: `
      Tomates|Tomate|Tomates grappe|Tomates cœur de bœuf|Tomates allongées, Tomates cerises|Tomate cerise|Tomates cocktail,
      Concombre|Concombres|Mini concombres, Courgettes|Courgette, Poivrons|Poivron|Poivron rouge|Poivron vert|Poivron jaune,
      Carottes|Carotte|Carottes nouvelles, Pommes de terre|Pomme de terre|Patates|Patate|Pommes de terre nouvelles|Grenailles|Pommes de terre à chair ferme,
      Patates douces|Patate douce, Oignons|Oignon|Oignons rouges|Oignon rouge|Oignons jaunes|Échalotes|Échalote|Echalotes,
      Oignons nouveaux|Cébettes|Ciboules, Ail|Gousses d’ail|Tête d’ail, Gingembre|Gingembre frais, Curcuma frais,
      Brocolis|Brocoli|~Broccoli, Chou-fleur|Chou fleur, Romanesco, Champignons|Champignon|Champignons de Paris|Champignons bruns,
      Pleurotes, Shiitakés|Shiitake, Girolles|Chanterelles, Salade|Laitue|Mesclun|Salade verte|Jeunes pousses|Sachet de salade,
      Salade iceberg|Iceberg, Romaine|Laitue romaine|Cœurs de romaine|Sucrine|Sucrines, Mâche|Salade de mâche, Roquette,
      Endives|Endive|Chicorée, Radicchio|Trévise, Épinards|Epinards|Pousses d’épinards|Jeunes pousses d’épinards, Poireaux|Poireau, Céleri|Céleri branche,
      Céleri-rave|Céleri rave, Légumes pour pot-au-feu|Légumes à soupe, Aubergines|Aubergine, Courge|Butternut|Potiron|Potimarron|Citrouille,
      Betteraves|Betterave|Betterave cuite, Radis|Radis roses, Radis noir|Daikon, Chou-rave, Chou blanc|Chou|Chou pointu, Chou rouge, Chou frisé|Chou de Milan,
      Choux de Bruxelles, Chou kale|Kale, Chou chinois, Pak choï|Pak choi|Bok choy, Fenouil, Asperges|Asperge|Asperges vertes|Asperges blanches,
      Épis de maïs|Maïs doux épi, Pois gourmands|Mange-tout, Haricots verts|Haricots plats|Haricots beurre,
      Avocats|Avocat, Blettes|Bettes, Panais, Topinambours, Artichauts|Artichaut, Gombos|Okra, Navets|Navet|Rutabaga,
      Piments|Piment|Piment rouge|Jalapeños, Herbes fraîches|Herbes aromatiques|Fines herbes, Basilic, Persil|Persil plat|Persil frisé,
      Ciboulette, Coriandre|Coriandre fraîche, Aneth, Menthe|Menthe fraîche, Romarin, Thym, Sauge, Citronnelle, Cresson, Pousses|Germes|Graines germées|Pousses de soja,
      Légumes|Légumes frais, Crudités, Poêlée de légumes|Légumes pour wok
    `,
    obst: `
      Pommes|Pomme|Pommes Golden|Pink Lady|Gala|Granny Smith, Bananes|Banane, Poires|Poire, Oranges|Orange|Oranges à jus, Mandarines|Clémentines|Mandarine|Clémentine,
      Citrons|Citron, Citrons verts|Citron vert|Limes, Pamplemousse|Pamplemousses, Raisin|Raisins|Raisin blanc|Raisin noir, Fraises|Fraise,
      Framboises|Framboise, Myrtilles|Myrtille|Bleuets, Mûres|Mûre, Groseilles|Cassis, Groseilles à maquereau,
      Fruits rouges|Baies, Cerises|Cerise, Pêches|Pêche|Pêches plates, Nectarines|Nectarine|Brugnons, Abricots|Abricot,
      Prunes|Prune|Quetsches|Mirabelles, Kiwis|Kiwi, Mangues|Mangue, Ananas, Melon|Pastèque|Melon charentais,
      Grenade|Grenades, Figues|Figue, Fruits de la passion|Maracuja, Papaye, Physalis, Kakis|Kaki, Rhubarbe, Fruits|Fruits frais, Litchis|Litchi,
      Noix de coco, Coings
    `,
    brot: `
      Pain|Pain complet|Pain de campagne|Pain aux céréales|Pain de seigle|Pain au levain|Miche|Boule, Pain de mie|Pain toast|Pain de mie complet,
      Petits pains|Petit pain|Pains au lait|Pain au lait, Bretzels|Bretzel, Baguette|Baguettes|Tradition|Flûte|Ficelle, Ciabatta, Croissants|Croissant|Pains au chocolat|Chocolatines|Viennoiseries,
      Pain suédois|Cracottes|Biscottes, Pain pita|Pita|Galettes|Naan|Pain naan, Pumpernickel, Pains précuits|Baguettes précuites,
      Pains à burger|Buns|Pains burger, Pains à hot-dog, Gâteau|Gâteaux|Quatre-quarts, Brioche|Brioches|Brioche tranchée, Tortillas|Wraps|Galettes de blé,
      Bagels|Bagel, Muffins anglais|Muffins, Beignets|Donuts, Madeleines, Crêpes|Galettes bretonnes, Pain d’épices
    `,
    molkerei: `
      Lait|Lait demi-écrémé|Lait entier|Lait écrémé|Lait frais|Demi-écrémé, Yaourt|Yaourts|Yogourt|Yaourt nature|Yaourts aux fruits|~Yahourt|~Yaourth,
      Yaourt grec|Yaourt à la grecque, Skyr, Fromage blanc|Faisselle|Petits suisses, Crème|Crème liquide|Crème entière|Crème fleurette|Crème légère|Crème fouettée|Chantilly,
      Crème fraîche|Crème épaisse|Crème fraiche, Beurre|Beurre doux|Beurre demi-sel|Beurre salé, Beurre aux herbes,
      Margarine|Pâte à tartiner végétale, Œufs|Oeufs|Oeuf|Œuf|Œufs bio|Œufs plein air, Babeurre|Lait ribot, Kéfir|Kefir, Yaourt à boire|Lait fermenté,
      Crème dessert|Danette|Flan|Crème au chocolat|Riz au lait|Liégeois, Tzatziki, Lait chocolaté|Lait aromatisé, Café glacé, Desserts|Desserts lactés,
      Mousse au chocolat, Crème anglaise
    `,
    kaese: `
      Fromage|Fromage en tranches|Tranches de fromage, Emmental|Emmental râpé, Comté, Gruyère|Gruyere, Beaufort, Gouda, Edam|Mimolette, Cantal|Tomme|Tomme de Savoie|Saint-Nectaire,
      Fromage râpé|Râpé|Fromage à pizza, Parmesan|Parmigiano|Grana Padano, Pecorino, Mozzarella|Mozzarella di bufala|Billes de mozzarella,
      Burrata, Feta, Halloumi, Fromage frais|Philadelphia|St Môret|Carré frais|Boursin|Fromage à tartiner, Cottage cheese, Mascarpone, Ricotta,
      Camembert, Brie|Coulommiers, Chèvre|Fromage de chèvre|Bûche de chèvre|Crottin de chavignol, Roquefort|Bleu|Bleu d’Auvergne|Fourme d’Ambert|Gorgonzola,
      Raclette|Fromage à raclette, Reblochon|Tartiflette fromage, Munster, Morbier, Manchego, Cheddar, Babybel|Vache qui rit|Kiri, Mont d’Or
    `,
    fleisch: `
      Viande hachée|Steak haché|Steaks hachés|Haché de bœuf|Bœuf haché|Boeuf haché|Haché|Chair à saucisse, Blanc de poulet|Blancs de poulet|Filet de poulet|Escalope de poulet|Aiguillettes de poulet,
      Poulet|Poulet entier|Poulet rôti|Cuisses de poulet|Pilons de poulet|Ailes de poulet|Hauts de cuisse, Dinde|Escalope de dinde|Blanc de dinde|Filet de dinde,
      Escalope|Escalopes|Escalope de veau|Escalope panée, Steak|Entrecôte|Bavette|Faux-filet|Rumsteck|Côte de bœuf|Onglet, Bœuf|Boeuf|Bœuf bourguignon|Pot-au-feu|Rôti de bœuf|Viande à braiser,
      Porc|Côtes de porc|Côtelettes de porc|Filet mignon|Rôti de porc|Échine de porc|Poitrine de porc, Agneau|Gigot|Côtelettes d’agneau|Souris d’agneau|Épaule d’agneau,
      Boulettes de viande|Boulettes|Hamburgers|Burgers, Saucisses|Saucisse|Chipolatas|Merguez|Saucisses de Toulouse|Saucisses de Strasbourg|Knacks|Francfort,
      Saucisson|Saucisson sec|Salami|Rosette, Jambon|Jambon blanc|Jambon cuit|Jambon de Paris, Jambon cru|Jambon de Bayonne|Jambon de Parme|Jambon serrano|Prosciutto,
      Lardons|Bacon|Poitrine fumée|Allumettes de lardons|Pancetta, Charcuterie|Assortiment de charcuterie, Pâté|Terrine|Rillettes|Mousse de foie,
      Mortadelle, Chorizo, Andouillette|Boudin noir|Boudin blanc, Canard|Magret de canard|Cuisses de canard|Confit de canard, Viande pour kebab|Gyros, Veau|Blanquette de veau,
      Foie gras, Lapin, Viande
    `,
    fisch: `
      Saumon|Pavé de saumon|Filet de saumon|Saumon frais, Saumon fumé, Truite|Filet de truite, Truite fumée, Cabillaud|Dos de cabillaud|Colin|Lieu noir|Merlu|Poisson blanc|Filets de poisson,
      Crevettes|Gambas|Crevettes roses|Crevettes décortiquées|Scampi, Hareng|Harengs|Filets de hareng|Harengs marinés|Rollmops, Maquereau|Maquereaux|Maquereau fumé,
      Daurade|Dorade|Bar|Loup de mer|Sandre|Sole|Lieu jaune|Merlan, Calamars|Encornets|Seiches|Poulpe, Moules|Palourdes|Coques|Coquilles Saint-Jacques|Huîtres,
      Surimi|Bâtonnets de surimi, Crabe|Tourteau, Poisson, Thon frais|Steak de thon, Sardines fraîches, Lotte, Espadon, Homard|Langoustines, Truite saumonée
    `,
    kuehlveg: `
      Tofu|Tofu fumé|Tofu soyeux|Tofu nature, Tempeh, Seitan, Steaks végétaux|Burger végétarien|Burgers végétaux|Saucisses végétales|Haché végétal|Galettes de légumes,
      Falafels|Falafel, Houmous|Hummus|Humus, Gnocchis|Gnocchi, Pâtes fraîches|Tortellinis|Tortellini|Raviolis frais|Ravioles|Raviolis,
      Pâte à pizza, Pâte feuilletée, Pâte brisée|Pâte sablée, Pâte filo|Feuilles de brick, Pâte à croissants|Pâte à cookies,
      Tartinables|Tartinade|Tartinade végétale, Antipasti|Olives marinées|Tapenade, Pesto frais, Kimchi, Taboulé|Salade composée|Carottes râpées|Céleri rémoulade,
      Sandwichs|Wraps préparés, Quiche|Quiche lorraine|Tarte salée, Plats préparés frais|Plat cuisiné|Soupe fraîche|Gaspacho, Guacamole
    `,
    fruehstueck: `
      Flocons d’avoine|Avoine|Porridge, Muesli|Granola|Muesli croustillant|Muesli aux fruits, Céréales|Corn flakes|Céréales petit-déjeuner|Chocapic|Special K|Trésor|Frosties,
      Nutella|Pâte à tartiner|Pâte à tartiner chocolat, Confiture|Confiture de fraises|Confiture d’abricots|Marmelade|Gelée, Miel, Beurre de cacahuète, Purée d’amandes|Purée de noisettes|Purée de noix de cajou,
      Café|Café en grains|Café moulu|Espresso|Café filtre, Dosettes de café|Capsules de café|Nespresso|Capsules|Dosettes|Senseo, Café soluble|Nescafé|Café instantané, Filtres à café,
      Thé|Thé noir|Sachets de thé|Infusion|Tisane|Thé aux fruits, Thé vert, Thé à la menthe|Menthe poivrée infusion, Camomille|Verveine, Thé au gingembre, Chaï|Chai,
      Chocolat en poudre|Cacao|Cacao en poudre|Poulain|Nesquik|Chocolat chaud, Graines de chia|Chia, Graines de lin, Protéines en poudre|Whey, Sirop d’érable|Sirop d’agave|Sirop de dattes,
      Pâte à crêpes|Préparation pour crêpes, Ovomaltine, Biscottes petit-déjeuner, Pain d’épices tranché
    `,
    nudeln: `
      Spaghettis|Spaghetti|~Spagettis|~Spaghetis, Pâtes|Pâtes sèches|Nouilles, Penne|Pennes, Fusilli|Torsades, Farfalle|Papillons, Rigatoni, Tagliatelles|Tagliatelle|Pappardelle|Fettuccine,
      Linguine, Macaronis|Coquillettes|Coudes, Feuilles de lasagne|Lasagnes feuilles|Plaques de lasagne, Pâtes complètes, Nouilles aux œufs|Vermicelles|Cheveux d’ange,
      Riz|Riz long|Riz blanc|Riz complet|Riz rond|Riz en sachets|Riz cuisson rapide, Riz basmati|Basmati, Riz thaï|Riz jasmin, Riz à risotto|Arborio|Risotto,
      Riz rond pour riz au lait, Riz sauvage, Riz à sushi, Semoule|Couscous, Boulgour, Quinoa, Lentilles|Lentilles vertes|Lentilles corail|Lentilles du Puy|Lentilles beluga, Polenta,
      Purée en flocons|Purée instantanée|Mousline, Knödels, Vermicelles de riz|Nouilles de riz|Vermicelles chinois, Nouilles instantanées|Ramen|Udon|Soba|Nouilles chinoises,
      Millet, Orge perlé|Orge, Sarrasin|Blé noir, Orzo|Pâtes langues d’oiseau, Pois chiches secs, Haricots secs, Ebly|Blé
    `,
    konserven: `
      Concentré de tomates|Double concentré de tomates, Coulis de tomates|Passata|Purée de tomates, Tomates concassées|Tomates pelées|Tomates en conserve|Pulpe de tomates|Tomates en dés,
      Lait de coco|Crème de coco, Pois chiches, Haricots rouges, Haricots blancs|Flageolets|Lingots, Haricots noirs, Haricots à la sauce tomate|Baked beans,
      Maïs|Maïs en conserve|Maïs doux, Thon|Thon en boîte|Thon au naturel|Miettes de thon, Sardines|Sardines à l’huile, Anchois, Olives|Olives vertes|Olives noires|Olives Kalamata,
      Câpres, Cornichons|Pickles, Choucroute, Chou rouge en bocal, Compote|Compote de pommes|Compotes|Gourdes de compote|Purée de fruits, Salsifis en conserve,
      Fruits au sirop|Pêches au sirop|Ananas en boîte|Fruits en conserve, Soupe|Velouté|Soupe en brique|Soupe déshydratée, Sauce tomate|Sauce pour pâtes|Sauce bolognaise|Sauce arrabbiata|Sauce napolitaine,
      Pesto|Pesto vert|Pesto rouge, Ketchup, Mayonnaise|Mayo|Sauce tartare|Sauce rémoulade, Moutarde|Moutarde de Dijon|Moutarde à l’ancienne,
      Sauce barbecue|Sauce BBQ, Sauce soja|Tamari|Shoyu, Pâte de curry|Curry rouge|Curry vert|Sauce curry, Tahini|Tahin|Crème de sésame,
      Sauce cacahuète|Sauce satay, Sauce chili douce|Sauce pimentée|Sauce piquante|Harissa, Sriracha, Tabasco, Sauce poisson|Nuoc-mâm|Nuoc mam, Sauce huître, Sauce hoisin, Sauce teriyaki,
      Tomates séchées, Cœurs d’artichauts, Betteraves en bocal, Chutney|Chutney de mangue, Plats cuisinés|Raviolis en boîte|Cassoulet|Petit salé|Chili con carne,
      Sauce salsa|Dip, Champignons en conserve|Champignons de Paris en boîte, Jacquier|Jackfruit, Raifort, Sauce Worcestershire, Petits pois carottes|Petits pois en conserve|Macédoine de légumes,
      Sauce béarnaise|Sauce hollandaise|Sauces, Vinaigrette en bouteille, Fond de veau|Fond de volaille
    `,
    oel: `
      Huile d’olive|Huile d’olive vierge extra, Huile|Huile de tournesol|Huile de colza|Huile végétale|Huile de friture|Huile pour cuisson, Huile de coco, Huile de sésame, Huile de noix|Huile de lin,
      Vinaigre balsamique|Balsamique|Crème de balsamique, Vinaigre|Vinaigre de vin|Vinaigre de cidre|Vinaigre blanc|Vinaigre de xérès|Vinaigre d’alcool, Jus de citron|Jus de citron vert,
      Sel|Sel fin|Gros sel|Sel de mer|Fleur de sel, Poivre|Poivre noir|Poivre en grains|Poivre moulu|Poivre blanc|Moulin à poivre, Épices|Épice|Assaisonnement,
      Paprika|Paprika fumé|Piment doux, Curry|Curry en poudre, Curcuma|Curcuma en poudre, Cumin|Cumin moulu, Carvi,
      Cannelle|Cannelle en poudre|Bâtons de cannelle, Muscade|Noix de muscade, Origan|Origan séché, Piment en poudre|Flocons de piment|Piment de Cayenne|Piment d’Espelette,
      Ail en poudre|Ail semoule|Oignon en poudre, Herbes de Provence|Herbes italiennes|Herbes séchées, Laurier|Feuilles de laurier, Clous de girofle, Garam masala, Ras el hanout,
      Zaatar|Za’atar, Sumac, Vanille|Gousse de vanille|Extrait de vanille, Bouillon|Bouillon cube|Cube de bouillon|Bouillon de légumes|Bouillon Kub, Bouillon de volaille|Bouillon de poule,
      Bouillon de bœuf|Fond brun, Vinaigrette|Sauce salade, Graines de moutarde, Levure maltée|Levure nutritionnelle, Mélange barbecue|Épices à steak|Épices cajun|Épices fajitas|Épices tacos,
      Sel aux herbes|Sel de céleri, Gingembre en poudre, Coriandre en graines|Coriandre moulue, Quatre-épices, Cinq-épices, Thym séché, Persil séché, Safran
    `,
    backen: `
      Farine|Farine de blé|Farine T45|Farine T55|Farine à gâteau, Farine de pain|Farine T65, Farine complète|Farine de seigle|Farine d’épeautre|Farine de sarrasin,
      Sucre|Sucre en poudre|Sucre semoule|Sucre blanc|Sucre en morceaux, Sucre roux|Cassonade|Sucre de canne|Vergeoise, Sucre glace,
      Levure chimique|Poudre à lever, Bicarbonate|Bicarbonate de soude, Levure boulangère|Levure sèche|Levure fraîche, Sucre vanillé, Fécule de maïs|Maïzena|Amidon|Fécule de pomme de terre,
      Chocolat pâtissier|Chocolat à cuire|Pépites de chocolat|Chocolat noir pâtissier, Amandes|Poudre d’amandes|Amandes effilées|Amandes en poudre, Noisettes|Poudre de noisettes,
      Noix|Cerneaux de noix, Fruits secs|Mélange de noix, Noix de cajou, Pignons de pin|Pignons, Graines de tournesol, Graines de courge, Sésame|Graines de sésame,
      Raisins secs|Raisins de Corinthe, Dattes|Dattes Medjool, Abricots secs|Mangue séchée|Cranberries séchées|Canneberges|Pruneaux|Figues sèches, Noix de coco râpée|Coco râpée,
      Gélatine|Feuilles de gélatine|Agar-agar, Chapelure|Panko, Semoule fine|Semoule de blé dur, Vermicelles colorés|Décorations|Vermicelles chocolat, Préparation pour gâteau|Préparation pour brownies,
      Préparation pour flan|Flan en poudre, Nappage, Pâte d’amande|Massepain, Colorant alimentaire, Pistaches, Noix de pécan, Noix de macadamia, Noix du Brésil,
      Lait concentré sucré|Lait concentré, Lait concentré non sucré, Caramel|Sauce caramel, Cerises confites|Fruits confits, Arômes|Fleur d’oranger|Rhum arôme
    `,
    suess: `
      Chocolat|Tablette de chocolat|Chocolat noir|Chocolat au lait|Chocolat blanc|Milka|Lindt|Côte d’Or, Biscuits|Gâteaux secs|Petit beurre|Cookies|Sablés|Prince|BN|Petits LU|Oreo,
      Chips|Chips de pommes de terre|Pringles|Chips nature, Tortilla chips|Nachos, Bonbons|Haribo|Oursons|Bonbons gélifiés|Fraises Tagada|Dragibus, Bretzels apéritif|Bâtonnets salés|Mini bretzels,
      Crackers|Biscuits apéritif|Tuc|Crackers au fromage, Pop-corn|Popcorn, Barres de céréales|Barres protéinées|Barres chocolatées|Snickers|Mars|Twix|Kinder Bueno|KitKat, Sucettes|Pastilles|Bonbons à la menthe,
      Chewing-gum|Chewing gum|Hollywood, Cacahuètes|Cacahuètes grillées|Cacahuètes salées, Mélange de fruits secs|Mélange apéritif, Galettes de riz|Galettes de maïs, Chocolats|Pralinés|Ferrero Rocher|Boîte de chocolats|Mon Chéri,
      Pain d’épices|Spéculoos, Gaufres|Gaufrettes, Friandises|Confiseries|Sucreries, Réglisse|Carambar|Car en sac, Kinder|Chocolat Kinder, Noix salées|Pistaches salées, Olives apéritif,
      Guimauves|Chamallows|Marshmallows, Cônes|Cornets de glace, Madeleines paquet|Brownies|Muffins emballés|Barquettes
    `,
    pflanzendrink: `
      Lait d’avoine|Boisson à l’avoine|Boisson avoine|Oatly|Avoine barista, Lait de soja|Boisson soja|Boisson au soja|Soja barista, Lait d’amande|Boisson amande|Boisson à l’amande,
      Lait de riz|Boisson riz, Boisson coco|Lait de coco à boire, Lait végétal|Boisson végétale|Boissons végétales, Boisson aux pois, Boisson cajou|Lait de noisette|Boisson noisette,
      Lait UHT|Lait longue conservation|Lait stérilisé|Lait en brique, Lait en poudre|Lait concentré café, Crème pour café|Blanchisseur à café
    `,
    getraenke: `
      Eau|Eau minérale|Eau gazeuse|Eau pétillante|Eau plate|Bouteilles d’eau|Évian|Cristaline|Badoit|Perrier|San Pellegrino, Jus|Jus d’orange|Jus de pomme|Jus multifruits|Jus de raisin|Pur jus|Jus d’ananas|Jus de tomate,
      Pomme pétillante|Jus pétillant, Cola|Coca-Cola|Coca|Pepsi|Coca Zero, Limonade|Sodas|Soda|Fanta|Sprite|Orangina|Schweppes agrumes|Diabolo,
      Thé glacé|Ice tea|Lipton ice tea, Bière|Bières|Blonde|Brune|Ambrée|Bière blanche|Pils|Pack de bière, Panaché|Monaco, Bière sans alcool|Bière 0,0,
      Vin|Vin rouge|Vin blanc|Rosé|Vin rosé|Bordeaux|Côtes du Rhône, Champagne|Crémant|Vin mousseux|Prosecco|Cava, Gin, Vodka, Rhum, Whisky|Whiskey|Bourbon, Apéritif|Pastis|Ricard|Aperol|Campari|Martini|Kir,
      Tonic|Schweppes|Bitter lemon|Ginger ale|Ginger beer, Boisson énergisante|Red Bull|Monster, Maté|Club Mate, Kombucha, Smoothie|Smoothies,
      Shots de gingembre|Shots, Sirop|Sirop de grenadine|Sirop de menthe|Sirop de fleur de sureau, Cidre|Cidre brut|Cidre doux, Boisson isotonique|Powerade|Gatorade, Eau de coco, Liqueur|Calvados|Cognac
    `,
    tk: `
      Pizza surgelée|Pizza|Pizzas, Frites|Frites surgelées|Frites au four|Potatoes|Pommes noisettes|Pommes dauphines|Galettes de pommes de terre|Rösti,
      Poisson pané|Bâtonnets de poisson|Fish sticks|Colin pané, Légumes surgelés|Épinards surgelés|Poêlée surgelée|Mélange de légumes surgelés|Haricots verts surgelés, Petits pois|Petits pois surgelés|Petits pois extra-fins,
      Fruits rouges surgelés|Framboises surgelées|Myrtilles surgelées|Fruits surgelés, Mangue surgelée|Mix smoothie,
      Glace|Glaces|Crème glacée|Sorbet|Magnum|Ben & Jerry’s|Ben and Jerrys|Häagen-Dazs|Cônes glacés|Bâtonnets glacés|Esquimau, Edamame, Nuggets|Nuggets de poulet|Croquettes de poulet, Herbes surgelées,
      Pains surgelés|Viennoiseries surgelées|Croissants surgelés, Nems|Rouleaux de printemps|Samoussas, Lasagnes surgelées|Plats surgelés|Plats cuisinés surgelés, Glaçons|Glace pilée,
      Crevettes surgelées, Pâte feuilletée surgelée, Raviolis chinois|Gyoza|Dim sum|Bouchées vapeur, Tarte flambée|Flammekueche, Picard, Poisson surgelé, Poulet surgelé,
      Pain à l’ail, Gaufres surgelées|Crêpes surgelées, Maïs surgelé
    `,
    drogerie: `
      Déodorant|Déo|Anti-transpirant|Déodorant bille|Déodorant spray|Déodorant stick, Dentifrice|Colgate|Signal|Sensodyne|Elmex|Parodontax|Fluocaril,
      Brosse à dents|Brosses à dents|Brossettes|Têtes de brosse à dents, Fil dentaire|Brossettes interdentaires|Cure-dents, Bain de bouche|Listerine,
      Gel douche|Crème de douche|Douche, Shampooing|Shampoing|Shampoing antipelliculaire, Après-shampooing|Après-shampoing|Démêlant, Masque capillaire|Soin capillaire|Huile capillaire,
      Gel coiffant|Laque|Cire coiffante|Crème coiffante|Mousse coiffante, Savon|Savon liquide|Savon pour les mains|Savonnette|Savon de Marseille, Crème pour les mains, Lait pour le corps|Crème pour le corps|Lait corporel|Crème hydratante,
      Crème visage|Crème de jour|Crème de nuit|Nivea|Soin visage, Crème solaire|Protection solaire|Lait solaire|Spray solaire|Après-soleil,
      Baume à lèvres|Stick à lèvres|Labello, Rasoirs|Lames de rasoir|Rasoirs jetables|Rasoir, Mousse à raser|Gel de rasage, Après-rasage|Aftershave,
      Cotons démaquillants|Disques de coton|Cotons, Cotons-tiges|Coton-tige, Coton|Coton hydrophile, Mouchoirs|Kleenex|Mouchoirs en papier|Boîte de mouchoirs,
      Papier toilette|Papier hygiénique|PQ|Rouleaux de papier toilette, Lingettes|Lingettes bébé|Papier toilette humide|Lingettes humides, Pansements|Sparadrap|Pansements ampoules|Compeed,
      Tampons|Serviettes hygiéniques|Protège-slips|Hygiène féminine|Coupe menstruelle, Préservatifs, Lime à ongles|Vernis à ongles|Dissolvant|Coupe-ongles,
      Maquillage|Mascara|Rouge à lèvres|Poudre|Anticernes|Fond de teint|Crayon khôl|Fard à paupières, Démaquillant|Eau micellaire|Lotion tonique|Gel nettoyant|Nettoyant visage,
      Parfum|Eau de toilette|Eau de parfum, Produit pour lentilles|Lentilles de contact|Sérum physiologique, Vitamines|Compléments alimentaires|Magnésium|Vitamine D|Zinc|Comprimés effervescents,
      Couches|Couches bébé|Pampers, Petits pots|Nourriture bébé|Compotes bébé|Lait infantile, Élastiques à cheveux|Barrettes|Brosse à cheveux|Peigne, Crème pour les pieds,
      Paracétamol|Doliprane|Ibuprofène|Aspirine, Pastilles pour la gorge|Sirop pour la toux|Spray nasal, Bouchons d’oreilles|Boules Quies, Bougie parfumée, Toilette intime, Gel hydroalcoolique
    `,
    haushalt: `
      Liquide vaisselle|Produit vaisselle|Paic|Mir|Fairy, Pastilles lave-vaisselle|Tablettes lave-vaisselle|Capsules lave-vaisselle|Finish|Sun|Lave-vaisselle poudre,
      Liquide de rinçage, Sel régénérant|Sel lave-vaisselle, Lessive|Lessive liquide|Lessive en poudre|Capsules de lessive|Ariel|Skip|Le Chat|Persil|X-tra|Lessive délicate,
      Adoucissant|Assouplissant|Soupline|Lenor, Détachant|Vanish|Anti-taches|Savon détachant, Nettoyant multi-usages|Nettoyant|Produit ménager|Nettoyant ménager|Mr Propre|Cif|Spray nettoyant,
      Nettoyant vitres|Lave-vitres|Produit vitres, Nettoyant salle de bain|Anticalcaire|Détartrant, Détartrant cafetière|Détartrant bouilloire, Nettoyant WC|Gel WC|Javel|Eau de Javel|Bloc WC|Harpic|Canard WC,
      Éponges|Éponge|Tampons à récurer|Éponge grattante|Paille de fer, Lavettes|Chiffons|Microfibres|Torchons|Serpillière, Essuie-tout|Sopalin|Papier absorbant|Rouleaux essuie-tout,
      Sacs poubelle|Sacs-poubelle|Sacs à ordures|Sacs compost|Sacs biodéchets, Papier aluminium|Papier alu|Aluminium, Film alimentaire|Film étirable, Papier cuisson|Papier sulfurisé,
      Sacs congélation|Sacs zip|Sachets fraîcheur|Sacs de congélation, Piles|Piles AA|Piles AAA|Piles LR6, Ampoules|Ampoule|Ampoule LED, Bougies|Bougies chauffe-plat, Allumettes|Briquet,
      Serviettes en papier|Serviettes de table, Assiettes en carton|Gobelets|Gobelets en carton|Pailles|Couverts jetables, Charbon de bois|Allume-feu|Allume-barbecue, Croquettes pour chat|Pâtée pour chat|Croquettes pour chien|Litière|Nourriture pour animaux|Friandises pour chien,
      Terreau|Engrais|Engrais pour plantes, Déboucheur|Destop|Déboucheur canalisations, Nettoyant four|Décapant four, Nettoyant sol|Nettoyant parquet|Produit sols, Vinaigre ménager|Vinaigre blanc ménager,
      Pinces à linge, Sacs d’aspirateur|Sacs aspirateur, Gants de ménage|Gants|Gants jetables, Désodorisant|Parfum d’ambiance|Febreze|Diffuseur, Antimites, Cirage, Plumeau
    `,
    sonstiges: ``,
  },

  // Beispiele für den Verlauf beim ersten Öffnen, damit Vorschläge und Schnellauswahl gleich etwas anbieten
  start: ['Lait', 'Pain', 'Baguette', 'Œufs', 'Beurre', 'Bananes', 'Pommes', 'Tomates', 'Concombre', 'Oignons', 'Pommes de terre', 'Emmental',
    'Yaourt', 'Blanc de poulet', 'Viande hachée', 'Pâtes', 'Riz', 'Café', 'Thé', 'Jus d’orange', 'Papier toilette', 'Liquide vaisselle',
    'Dentifrice', 'Saumon', 'Carottes', 'Courgettes', 'Crème fraîche', 'Chocolat', 'Chips', 'Tomates concassées', 'Mozzarella', 'Jambon'],

  // Typischer Vorrat: im Rezept-Prüfblatt standardmäßig abgewählt
  vorrat: ['Sel', 'Poivre', 'Poivre noir', 'Huile', 'Huile d’olive', 'Farine', 'Sucre', 'Eau', 'Vinaigre', 'Cannelle', 'Paprika',
    'Levure chimique', 'Curry', 'Muscade', 'Origan', 'Maïzena', 'Fécule de maïs', 'Sucre vanillé', 'Bouillon de légumes', 'Bouillon cube',
    'Piment en poudre', 'Cumin', 'Laurier', 'Bicarbonate', 'Sauce soja', 'Herbes de Provence', 'Thym'],
};
